import React, { useCallback, useState } from "react";
import { Redirect, router, useFocusEffect } from "expo-router";
import { Text, View } from "react-native";
import { apiFetch } from "@/lib/api";
import { colors } from "@/lib/theme";
import type { TodayResponse } from "@/lib/types";
import { Body, Card, Eyebrow, ErrorState, LoadingState, PrimaryButton, Screen, Title } from "@/components/ui";
import { CogniOrb } from "@/components/orb";

export default function TrainHomeScreen() {
  const [today, setToday] = useState<TodayResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setError(""); try { setToday(await apiFetch<TodayResponse>("/api/mobile/today")); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load training."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <LoadingState label="Choosing today’s training…" />; if (error && !today) return <ErrorState message={error} onRetry={() => void load()} />; if (today?.state === "onboarding") return <Redirect href="/onboarding" />;
  const questionCount = today?.state === "diagnostic" ? today.challenges?.length ?? 12 : today?.session?.challenges?.length ?? 0;
  if (today?.state === "lesson") return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><View style={{ alignItems: "center" }}><CogniOrb size={122} /></View><Eyebrow>{today.modeLabel ?? "Today’s insight"}</Eyebrow><Title>{today.lesson?.title ?? "Your short insight is ready"}</Title><Body muted>{today.lesson?.subtitle ?? "One short idea before today’s decisions."}</Body>{today.lesson?.scenario_context ? <Card><Eyebrow>Situation</Eyebrow><Body>{today.lesson.scenario_context}</Body></Card> : null}<PrimaryButton label="Start insight" onPress={() => router.push("/(tabs)/train/lesson")} />{error ? <Text style={{ color: "#ff9ac0" }}>{error}</Text> : null}</Screen>;
  if (today?.state === "diagnostic") return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><View style={{ alignItems: "center" }}><CogniOrb size={122} /></View><Eyebrow>Starting check</Eyebrow><Title>Find your best starting point</Title><Body muted>{questionCount} short decisions across evidence, reasoning, AI verification, bias and uncertainty. Your existing skill history is preserved.</Body><Card><Eyebrow>Why this comes first</Eyebrow><Body>Cogni uses a shared core plus situations relevant to your learning context so your scores stay comparable while the experience feels useful.</Body></Card><PrimaryButton label={today.answeredChallengeIds?.length ? "Continue starting check" : "Start starting check"} onPress={() => router.push("/(tabs)/train/session")} /></Screen>;
  if (today?.state === "training") { const answered = today.session?.answeredChallengeIds?.length ?? 0; return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><View style={{ alignItems: "center" }}><CogniOrb size={116} /></View><Eyebrow>{today.modeLabel ?? "Today’s training"}</Eyebrow><Title>{answered ? "Keep going" : "Your decisions are ready"}</Title><Body muted>{answered ? `${answered} of ${questionCount} questions complete.` : `${questionCount} situations chosen around the skills that will give you the most value today.`}</Body><PrimaryButton label={answered ? "Continue training" : "Start training"} onPress={() => router.push("/(tabs)/train/session")} /></Screen>; }
  if (today?.state === "complete") return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><View style={{ alignItems: "center" }}><CogniOrb size={108} /></View><Eyebrow>Daily goal complete</Eyebrow><Title>Judgement strengthened</Title><Body muted>Today’s core session is done. Training stays open whenever you want another three-question round.</Body><Card><Eyebrow>Keep building</Eyebrow><Body>Pick the skill you want to work on next. Cogni will prefer questions you haven’t seen before.</Body><PrimaryButton label="Choose a skill to practise" onPress={() => router.push("/(tabs)/skills")} /></Card></Screen>;
  return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><Card><Eyebrow>Today’s training</Eyebrow><Title size={27}>Not ready yet</Title><Body muted>{today?.message ?? "Cogni couldn’t prepare a suitable set right now."}</Body><PrimaryButton label="Try again" onPress={() => void load(true)} /></Card></Screen>;
}
