import React, { useCallback, useState } from "react";
import { Redirect, router, useFocusEffect } from "expo-router";
import { Text, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { apiFetch } from "@/lib/api";
import { colors } from "@/lib/theme";
import type { TodayResponse } from "@/lib/types";
import { Body, Card, Eyebrow, ErrorState, LoadingState, PrimaryButton, ProgressBar, Screen, Title } from "@/components/ui";
import { CogniOrb } from "@/components/orb";

function Hero({ eyebrow, title, body, cta, onPress, progress }: { eyebrow: string; title: string; body: string; cta: string; onPress: () => void; progress?: number }) {
  return <LinearGradient colors={["rgba(34,45,106,.98)", "rgba(13,18,49,.99)"]} style={{ borderRadius: 28, borderWidth: 1, borderColor: colors.line, padding: 18, overflow: "hidden" }}><View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><View style={{ flex: 1, gap: 7 }}><Eyebrow>{eyebrow}</Eyebrow><Title size={28}>{title}</Title><Body muted style={{ fontSize: 14.5, lineHeight: 21 }}>{body}</Body></View><View style={{ marginRight: -26 }}><CogniOrb size={104} /></View></View>{typeof progress === "number" ? <View style={{ marginTop: 8, gap: 6 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Text style={{ color: colors.muted, fontSize: 12.5 }}>Session progress</Text><Text style={{ color: colors.cyan, fontWeight: "900", fontSize: 12.5 }}>{Math.round(progress)}%</Text></View><ProgressBar value={progress} /></View> : null}<View style={{ marginTop: 12 }}><PrimaryButton label={cta} onPress={onPress} /></View></LinearGradient>;
}

export default function TrainHomeScreen() {
  const [today, setToday] = useState<TodayResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setError(""); try { setToday(await apiFetch<TodayResponse>("/api/mobile/today")); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load training."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <LoadingState label="Choosing today’s training…" />; if (error && !today) return <ErrorState message={error} onRetry={() => void load()} />; if (today?.state === "onboarding") return <Redirect href="/onboarding" />;
  const questionCount = today?.state === "diagnostic" ? today.challenges?.length ?? 12 : today?.session?.challenges?.length ?? 0;
  if (today?.state === "lesson") return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><Hero eyebrow={today.modeLabel ?? "Today’s insight"} title={today.lesson?.title ?? "Your short insight is ready"} body={today.lesson?.subtitle ?? "One short idea before today’s decisions."} cta="Start insight" onPress={() => router.push("/(tabs)/train/lesson")} />{today.lesson?.scenario_context ? <Card><Eyebrow>Situation</Eyebrow><Body>{today.lesson.scenario_context}</Body></Card> : null}{error ? <Text style={{ color: "#ff9ac0" }}>{error}</Text> : null}</Screen>;
  if (today?.state === "diagnostic") { const answered = today.answeredChallengeIds?.length ?? 0; const progress = questionCount ? answered / questionCount * 100 : 0; return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><Hero eyebrow="Starting check" title="Find your best starting point" body={`${questionCount} short decisions across evidence, reasoning, AI verification, bias and uncertainty.`} cta={answered ? "Continue starting check" : "Start starting check"} onPress={() => router.push("/(tabs)/train/session")} progress={progress} /><Card><Eyebrow>Why this comes first</Eyebrow><Body>Cogni uses a shared core plus situations relevant to your context so your scores stay comparable while the experience feels useful.</Body></Card></Screen>; }
  if (today?.state === "training") { const answered = today.session?.answeredChallengeIds?.length ?? 0; const progress = questionCount ? answered / questionCount * 100 : 0; return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><Hero eyebrow={today.modeLabel ?? "Today’s training"} title={answered ? "Keep the momentum going" : "Your decisions are ready"} body={answered ? `${answered} of ${questionCount} questions complete.` : `${questionCount} situations chosen around the skills that will give you the most value today.`} cta={answered ? "Continue training" : "Start training"} onPress={() => router.push("/(tabs)/train/session")} progress={progress} /></Screen>; }
  if (today?.state === "complete") return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><Hero eyebrow="Daily goal complete" title="Judgement strengthened" body="Today’s core session is done. Training stays open whenever you want another focused round." cta="Choose a skill to practise" onPress={() => router.push("/(tabs)/skills")} progress={100} /><Card><Eyebrow>Keep building</Eyebrow><Body>Pick the skill you want to work on next. Cogni will prefer questions you haven’t seen before.</Body></Card></Screen>;
  return <Screen refreshing={refreshing} onRefresh={() => void load(true)}><Card><Eyebrow>Today’s training</Eyebrow><Title size={27}>Not ready yet</Title><Body muted>{today?.message ?? "Cogni couldn’t prepare a suitable set right now."}</Body><PrimaryButton label="Try again" onPress={() => void load(true)} /></Card></Screen>;
}
