import React, { useCallback, useState } from "react";
import { Redirect, router, useFocusEffect } from "expo-router";
import { Text, TextInput, View } from "react-native";
import { apiFetch } from "@/lib/api";
import { colors } from "@/lib/theme";
import type { TodayResponse } from "@/lib/types";
import { Body, Card, Eyebrow, ErrorState, LoadingState, PrimaryButton, Screen, Title } from "@/components/ui";

export default function LessonScreen() {
  const [today, setToday] = useState<TodayResponse | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [thought, setThought] = useState(""); const [revealed, setRevealed] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setToday(await apiFetch<TodayResponse>("/api/mobile/today")); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load today’s insight."); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <LoadingState />; if (error && !today) return <ErrorState message={error} onRetry={() => void load()} />; if (today?.state === "onboarding") return <Redirect href="/onboarding" />; if (today?.state === "diagnostic" || today?.state === "training") return <Redirect href="/(tabs)/train/session" />; if (today?.state === "complete") return <Redirect href="/(tabs)/train" />; if (today?.state !== "lesson" || !today.lesson) return <ErrorState message="Today’s insight isn’t available right now." onRetry={() => void load()} />;
  const lesson = today.lesson;
  async function complete() { setBusy(true); setError(""); try { await apiFetch<{ ok: boolean; xpEarned: number }>("/api/mobile/lesson/complete", { method: "POST", body: JSON.stringify({ lessonId: lesson.id }) }); router.replace("/(tabs)/train/session"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not finish this insight."); } finally { setBusy(false); } }
  return <Screen><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 }}><Eyebrow>{today.modeLabel ?? "Today’s insight"}</Eyebrow><Text style={{ color: colors.muted, fontWeight: "700" }}>{lesson.estimated_minutes} min</Text></View><Title>{lesson.emoji} {lesson.title}</Title><Body muted>{lesson.subtitle}</Body>{lesson.scenario_context ? <Card><Eyebrow>Situation</Eyebrow><Body>{lesson.scenario_context}</Body></Card> : null}<Card><Eyebrow>The story</Eyebrow><Body>{lesson.content.story}</Body></Card><Card><Eyebrow>The twist</Eyebrow><Body>{lesson.content.twist}</Body></Card><Card><Eyebrow>Key idea</Eyebrow><Body>{lesson.content.principle}</Body></Card><Card><Eyebrow>Your turn</Eyebrow><Title size={25}>What do you think?</Title><Body>{lesson.content.try_it}</Body><TextInput multiline value={thought} onChangeText={setThought} placeholder="Write one sentence. This stays on your device and isn’t graded." placeholderTextColor={colors.soft} style={{ minHeight: 120, textAlignVertical: "top", borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, color: colors.text, padding: 14, fontSize: 17, lineHeight: 24 }} />{!revealed ? <PrimaryButton label="Reveal the thinking move" disabled={thought.trim().length < 3} onPress={() => setRevealed(true)} /> : null}</Card>{revealed ? <><Card style={{ borderColor: "rgba(41,214,125,.35)" }}><Eyebrow>The reveal</Eyebrow><Body>{lesson.content.reveal}</Body></Card><Card><Eyebrow>Why this matters with AI</Eyebrow><Body>{lesson.content.ai_age}</Body></Card>{error ? <Text selectable style={{ color: "#ff9ac0" }}>{error}</Text> : null}<PrimaryButton label={busy ? "Saving…" : "Complete insight +5 XP"} disabled={busy} onPress={() => void complete()} /></> : null}</Screen>;
}
