import React, { useCallback, useState } from "react";
import { router, useFocusEffect } from "expo-router";
import { Text, TextInput, View } from "react-native";
import { apiFetch } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { colors } from "@/lib/theme";
import type { MobileProfileResponse } from "@/lib/types";
import { Body, Card, Eyebrow, ErrorState, LoadingState, Pill, PrimaryButton, Screen, Title } from "@/components/ui";
const audienceNames: Record<string, string> = { university_student: "University student", graduate_early_career: "Graduate / early career", junior_professional: "Junior professional", management: "Management", executive: "Executive" };
const inputStyle = { minHeight: 50, borderRadius: 14, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.panel2, color: colors.text, paddingHorizontal: 13, fontSize: 16 } as const;

export default function ProfileScreen() {
  const { signOut } = useAuth(); const [data, setData] = useState<MobileProfileResponse | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState("");
  const [name, setName] = useState(""); const [functionArea, setFunctionArea] = useState(""); const [industry, setIndustry] = useState(""); const [goal, setGoal] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await apiFetch<MobileProfileResponse>("/api/mobile/profile"); setData(result); setName(result.profile.full_name ?? ""); setFunctionArea(result.profile.function_area ?? ""); setIndustry(result.profile.industry ?? ""); setGoal(result.profile.primary_goal ?? ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load profile."); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <LoadingState />; if (error && !data) return <ErrorState message={error} onRetry={() => void load()} />; if (!data) return null;
  async function save() { setBusy(true); setError(""); setSaved(""); try { const updated = await apiFetch<MobileProfileResponse>("/api/mobile/profile", { method: "POST", body: JSON.stringify({ fullName: name || null, functionArea: functionArea || null, industry: industry || null, primaryGoal: goal || null }) }); setData(updated); setSaved("Profile updated"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save profile."); } finally { setBusy(false); } }
  async function logout() { await signOut(); router.replace("/"); }
  const initials = (name || data.profile.email || "C").split(/\s+/).map((part) => part[0]).join("").slice(0,2).toUpperCase();
  return <Screen><View style={{ alignItems: "center", gap: 10 }}><View style={{ width: 82, height: 82, borderRadius: 41, alignItems: "center", justifyContent: "center", backgroundColor: colors.violet }}><Text style={{ color: colors.white, fontSize: 27, fontWeight: "900" }}>{initials}</Text></View><Title size={28}>{name || "Your Cogni profile"}</Title><Text selectable style={{ color: colors.muted, fontSize: 15 }}>{data.profile.email}</Text>{data.profile.audience_segment ? <Pill accent>{audienceNames[data.profile.audience_segment] ?? data.profile.audience_segment}</Pill> : null}</View><View style={{ flexDirection: "row", gap: 10 }}><Card style={{ flex: 1 }}><Eyebrow>XP</Eyebrow><Text style={{ color: colors.text, fontSize: 28, fontWeight: "900" }}>{data.profile.xp ?? 0}</Text></Card><Card style={{ flex: 1 }}><Eyebrow>Streak</Eyebrow><Text style={{ color: colors.text, fontSize: 28, fontWeight: "900" }}>🔥 {data.profile.current_streak ?? 0}</Text></Card></View><Card><Eyebrow>Learning context</Eyebrow><Body muted>Changing context never resets your scores, XP, streak or history. It changes the situations Cogni uses next.</Body><PrimaryButton label="Change learning context" secondary onPress={() => router.push("/onboarding")} /></Card><Card><Eyebrow>Make Cogni more relevant</Eyebrow><Text style={{ color: colors.text, fontWeight: "700" }}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor={colors.soft} style={inputStyle} /><Text style={{ color: colors.text, fontWeight: "700" }}>Function / study area</Text><TextInput value={functionArea} onChangeText={setFunctionArea} placeholder="Optional" placeholderTextColor={colors.soft} style={inputStyle} /><Text style={{ color: colors.text, fontWeight: "700" }}>Industry</Text><TextInput value={industry} onChangeText={setIndustry} placeholder="Optional" placeholderTextColor={colors.soft} style={inputStyle} /><Text style={{ color: colors.text, fontWeight: "700" }}>Primary goal</Text><TextInput value={goal} onChangeText={setGoal} placeholder="What do you most want to improve?" placeholderTextColor={colors.soft} style={inputStyle} />{saved ? <Text style={{ color: colors.green, fontWeight: "700" }}>{saved}</Text> : null}{error ? <Text selectable style={{ color: "#ff9ac0" }}>{error}</Text> : null}<PrimaryButton label={busy ? "Saving…" : "Save profile"} disabled={busy} onPress={() => void save()} /></Card><PrimaryButton label="Sign out" secondary onPress={() => void logout()} /></Screen>;
}
