"use client";
import{useState}from"react";import{useRouter}from"next/navigation";import type{AudienceSegment}from"@/lib/audience";import{INDUSTRY_OPTIONS,ORGANISATION_SCALE_OPTIONS,RESPONSIBILITY_OPTIONS,STUDY_STAGE_OPTIONS,contextFieldLabel,functionOptionsForAudience,goalOptionsForAudience,type ContextProfile}from"@/lib/context-profile";
function Select({id,label,value,onChange,options}:{id:string;label:string;value:string;onChange:(value:string)=>void;options:{value:string;label:string}[]}){return <><label htmlFor={id}>{label} <span className="cg-field-help">optional</span></label><select id={id} className="input" value={value} onChange={(event)=>onChange(event.target.value)}>{options.map((option)=><option key={option.value||"blank"} value={option.value}>{option.label}</option>)}</select></>}
export function ContextProfileForm({audience,initial,onboarding=false}:{audience:AudienceSegment;initial:ContextProfile;onboarding?:boolean}){
 const[functionArea,setFunctionArea]=useState(initial.functionArea??""),[industry,setIndustry]=useState(initial.industry??""),[primaryGoal,setPrimaryGoal]=useState(initial.primaryGoal??""),[studyStage,setStudyStage]=useState(initial.studyStage??""),[roleFocus,setRoleFocus]=useState(initial.roleFocus??""),[responsibilityScope,setResponsibilityScope]=useState(initial.responsibilityScope??""),[organisationScale,setOrganisationScale]=useState(initial.organisationScale??""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const router=useRouter();
 async function save(){if(busy)return;setBusy(true);setMessage("");try{const response=await fetch("/api/profile/context",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({functionArea,industry,primaryGoal,studyStage,roleFocus,responsibilityScope,organisationScale})});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(typeof body.error==="string"?body.error:"Could not save your context.");return}if(onboarding){router.push("/onboarding");router.refresh();return}setMessage("Personalisation details saved. Future content will use them where matching material is available.");router.refresh()}catch{setMessage("Connection interrupted. Try again.")}finally{setBusy(false)}}
 const isStudent=audience==="university_student",isManager=audience==="management",isExecutive=audience==="executive";
 return <div className="cg-context-profile-form"><Select id="context-function" label={contextFieldLabel(audience)} value={functionArea} onChange={setFunctionArea} options={functionOptionsForAudience(audience)}/>{isStudent&&<Select id="study-stage" label="Current stage" value={studyStage} onChange={setStudyStage} options={STUDY_STAGE_OPTIONS}/>} {!isStudent&&<Select id="context-industry" label="Industry" value={industry} onChange={setIndustry} options={INDUSTRY_OPTIONS}/>}<Select id="context-goal" label={isExecutive?"Primary decision focus":isManager?"Primary challenge":"Primary development goal"} value={primaryGoal} onChange={setPrimaryGoal} options={goalOptionsForAudience(audience)}/>{!isStudent&&<><label htmlFor="role-focus">Role focus <span className="cg-field-help">optional</span></label><input id="role-focus" className="input" value={roleFocus} onChange={(event)=>setRoleFocus(event.target.value)} maxLength={100} placeholder={isExecutive?"e.g. technology, operations, commercial":"e.g. projects, product, advisory"}/></>}{(isManager||isExecutive)&&<Select id="responsibility" label="Responsibility" value={responsibilityScope} onChange={setResponsibilityScope} options={RESPONSIBILITY_OPTIONS}/>} {isExecutive&&<Select id="org-scale" label="Organisation scale" value={organisationScale} onChange={setOrganisationScale} options={ORGANISATION_SCALE_OPTIONS}/>}<button type="button" className="cg-button cg-full" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":onboarding?"Save and continue":"Save personalisation"}</button>{onboarding&&<button type="button" className="cg-button secondary cg-full" disabled={busy} onClick={()=>{router.push("/onboarding");router.refresh()}}>Skip for now</button>}{message&&<p className="cg-form-message" aria-live="polite">{message}</p>}<p className="cg-audience-note">These details are optional. Cogni uses them only to prefer more relevant scenarios; it falls back safely to your broader learning context when needed.</p></div>
}
