import React,{useEffect,useMemo,useRef,useState}from"react";
import{AccessibilityInfo,Animated,Pressable,Text,View,type ScrollView}from"react-native";
import{LinearGradient}from"expo-linear-gradient";
import{apiFetch}from"@/lib/api";
import{useReducedMotion}from"@/lib/accessibility";
import{useFeedback}from"@/lib/feedback";
import{useNotebook}from"@/lib/notebook";
import{SaveIdeaButton,DeviceToolsNotice}from"@/components/practice-tools";
import{CogniIcon,SkillMotif,motifForSkill}from"@/components/visuals";
import{colors,radius,typography}from"@/lib/theme";
import type{AnswerResult,Challenge}from"@/lib/types";
import{Body,EditorialPanel,Eyebrow,PrimaryButton,ProgressBar,Screen,Title}from"@/components/ui";

type Mode="diagnostic"|"training"|"practice";type Category={id:string;label:string};type Props={mode:Mode;sessionId:string;challenges:Challenge[];answeredChallengeIds?:string[];modeLabel?:string;onComplete:()=>void|Promise<void>};
const formatLabels:Record<string,string>={single_choice:"Choose one",multi_select:"Choose all that apply",ranking:"Put in order",classification:"Sort into groups",triage:"What would you do?"};
function correctArray(value:unknown){return Array.isArray(value)?value.map(Number).filter(Number.isInteger):[];}function correctMap(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,string>:{};}function difficulty(value:number){if(value<40)return"Intro";if(value<60)return"Standard";if(value<75)return"Challenge";return"Advanced";}

function Choice({label,selected,correct,wrong,onPress,disabled,prefix,role="button",hint,accessibilityLabel}:{label:string;selected?:boolean;correct?:boolean;wrong?:boolean;onPress:()=>void;disabled?:boolean;prefix?:string;role?:"button"|"radio"|"checkbox";hint?:string;accessibilityLabel?:string}){
const reduced=useReducedMotion();const scale=useRef(new Animated.Value(1)).current;useEffect(()=>{if(reduced||(!correct&&!wrong)){scale.stopAnimation();scale.setValue(1);return;}Animated.sequence([Animated.spring(scale,{toValue:correct?1.018:.992,damping:13,stiffness:250,useNativeDriver:true}),Animated.spring(scale,{toValue:1,damping:15,stiffness:225,useNativeDriver:true})]).start();},[correct,reduced,scale,wrong]);
const border=correct?"rgba(126,230,185,.72)":wrong?"rgba(255,170,200,.58)":selected?colors.cyan:colors.line;const background=correct?"rgba(38,101,85,.25)":wrong?"rgba(89,42,68,.22)":selected?"rgba(32,79,114,.52)":"rgba(13,30,56,.70)";
return<Animated.View style={{transform:[{scale}]}}><Pressable accessibilityRole={role} accessibilityHint={hint} accessibilityLabel={`${accessibilityLabel??label}${correct?". Correct answer":wrong?". Your answer, worth reviewing":""}`} accessibilityState={{...(role==="button"?{selected:Boolean(selected)}:{checked:Boolean(selected)}),disabled:Boolean(disabled)}} disabled={disabled} onPress={onPress} style={({pressed})=>({minHeight:60,borderWidth:selected&&!correct&&!wrong?1.5:1,borderColor:border,backgroundColor:background,borderRadius:radius.md,paddingHorizontal:14,paddingVertical:13,flexDirection:"row",alignItems:"center",gap:12,opacity:pressed?.8:1})}>{prefix?<View style={{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:selected||correct?"rgba(109,235,255,.45)":colors.line,backgroundColor:selected||correct?"rgba(68,123,190,.24)":"rgba(13,28,52,.56)",alignItems:"center",justifyContent:"center"}}><Text style={{color:correct?colors.green:selected?colors.cyan:colors.muted,fontSize:13.5,...typography.label}}>{prefix}</Text></View>:null}<Text style={{flex:1,color:colors.text,fontSize:15.5,lineHeight:23,...typography.bodyMedium}}>{label}</Text>{correct?<View accessibilityLabel="Correct" style={{width:22,height:22,borderRadius:11,backgroundColor:"rgba(126,230,185,.20)",alignItems:"center",justifyContent:"center"}}><View style={{width:8,height:4,borderLeftWidth:1.8,borderBottomWidth:1.8,borderColor:colors.green,transform:[{rotate:"-45deg"}],marginTop:-2}}/></View>:wrong?<View accessibilityLabel="Incorrect" style={{width:20,height:20,alignItems:"center",justifyContent:"center"}}><View style={{position:"absolute",width:12,height:1.8,backgroundColor:colors.danger,transform:[{rotate:"45deg"}]}}/><View style={{position:"absolute",width:12,height:1.8,backgroundColor:colors.danger,transform:[{rotate:"-45deg"}]}}/></View>:selected?<View accessible={false} style={{width:10,height:10,borderRadius:5,backgroundColor:colors.cyan}}/>:null}</Pressable></Animated.View>;
}

export function QuestionRunner({mode,sessionId,challenges,answeredChallengeIds=[],modeLabel,onComplete}:Props){
const{playFeedback}=useFeedback();const reduced=useReducedMotion();const initialAnswered=useMemo(()=>new Set(answeredChallengeIds.filter(id=>challenges.some(challenge=>challenge.id===id))),[answeredChallengeIds,challenges]);const{recordPracticeDay}=useNotebook();const[visitIdeas,setVisitIdeas]=useState<{id:string;title:string;principle:string;application:string}[]>([]);const firstPending=challenges.findIndex(item=>!initialAnswered.has(item.id));const[index,setIndex]=useState(firstPending);const[answered,setAnswered]=useState(new Set(initialAnswered));const[selected,setSelected]=useState<number|null>(null);const[multi,setMulti]=useState<number[]>([]);const[ranking,setRanking]=useState<number[]>([]);const[classification,setClassification]=useState<Record<string,string>>({});const[confidence,setConfidence]=useState<number|null>(null);const[showSummary,setShowSummary]=useState(false);const[result,setResult]=useState<AnswerResult|null>(null);const[busy,setBusy]=useState(false);const[advancing,setAdvancing]=useState(false);const submitLock=useRef(false);const nextLock=useRef(false);const scrollRef=useRef<ScrollView>(null);const[error,setError]=useState("");const[startedAt,setStartedAt]=useState(Date.now());const resultCueChallengeRef=useRef<string|null>(null);const resultScrollChallengeRef=useRef<string|null>(null);
const challenge=challenges[index];const type=challenge?.interaction_type??"single_choice";const categories=((challenge?.interaction_config?.categories??[])as Category[]).filter(item=>item?.id&&item?.label);const requiredSelectionsRaw=Number(challenge?.interaction_config?.requiredSelections??challenge?.interaction_config?.required_selections??0);const requiredSelections=Number.isInteger(requiredSelectionsRaw)&&requiredSelectionsRaw>0?requiredSelectionsRaw:null;const correctList=correctArray(result?.correctAnswer);const correctGroups=correctMap(result?.correctAnswer);const progress=challenges.length?answered.size/challenges.length*100:0;
useEffect(()=>{setStartedAt(Date.now());submitLock.current=false;nextLock.current=false;setAdvancing(false);scrollRef.current?.scrollTo({y:0,animated:false});},[index]);
useEffect(()=>{if(!result||!challenge||resultCueChallengeRef.current===challenge.id)return;resultCueChallengeRef.current=challenge.id;const score=result.scoreFraction??(result.correct?1:0);const verdict=result.correct?"Correct.":score>=.5?"Partly right.":"Worth reviewing.";AccessibilityInfo.announceForAccessibility(`${verdict} You earned ${result.xpEarned} XP.`);playFeedback(result.correct?"correct":score>=.5?"review":"incorrect");},[challenge,playFeedback,result]);
async function finish(){if(nextLock.current)return;nextLock.current=true;setAdvancing(true);setError("");try{await onComplete();}catch{nextLock.current=false;setAdvancing(false);setError("We couldn’t open the next screen. Your answers are saved. Try again.");}}
if(!challenge)return<Screen><EditorialPanel><Title size={24}>{challenges.length?"You’re all caught up":"No questions available"}</Title><Body muted>{challenges.length?"Your answers are saved. Return to Train for your next step.":"Return to Train and try again."}</Body>{error?<Text accessibilityLiveRegion="assertive" style={{color:colors.danger}}>{error}</Text>:null}<PrimaryButton label={mode==="practice"?"Back to skills":"Back to training"} loading={advancing} onPress={()=>void finish()}/></EditorialPanel></Screen>;
const multiReady=requiredSelections?multi.length === requiredSelections:multi.length>0;const answerReady=type==="multi_select"?multiReady:type==="ranking"?ranking.length===challenge.options.length:type==="classification"?challenge.options.length>0&&challenge.options.every((_item,optionIndex)=>Boolean(classification[String(optionIndex)])):selected!==null;const ready=answerReady&&(!challenge.confidence_required||confidence!==null);
async function submit(){if(!ready||busy||result||submitLock.current)return;submitLock.current=true;setBusy(true);setError("");const responsePayload=type==="multi_select"?multi:type==="ranking"?ranking:type==="classification"?classification:selected;try{const response=await apiFetch<AnswerResult>("/api/mobile/answer",{method:"POST",body:JSON.stringify({challengeId:challenge.id,selectedIndex:type==="single_choice"||type==="triage"?selected:undefined,responsePayload,confidence:challenge.confidence_required?confidence:null,responseTimeMs:Math.min(3600000,Math.max(0,Date.now()-startedAt)),mode,sessionId})});setResult(response);setAnswered(current=>new Set([...current,challenge.id]));setVisitIdeas(current=>[...current.filter(idea=>idea.id!==challenge.id),{id:challenge.id,title:challenge.title,principle:response.thinkingPrinciple,application:response.application}]);void recordPracticeDay().catch(()=>undefined);}catch(caught){submitLock.current=false;setError(caught instanceof Error?caught.message:"Could not submit your answer. Please try again.");}finally{setBusy(false);}}
async function next(){if(!result||nextLock.current)return;const completed=new Set([...answered,challenge.id]);const nextIndex=challenges.findIndex((candidate,candidateIndex)=>candidateIndex>index&&!completed.has(candidate.id));if(nextIndex<0){playFeedback("complete");setShowSummary(true);scrollRef.current?.scrollTo({y:0,animated:false});return;}nextLock.current=true;setAdvancing(true);setIndex(nextIndex);setSelected(null);setMulti([]);setRanking([]);setClassification({});setConfidence(null);setResult(null);setError("");setStartedAt(Date.now());}
function choose(action:()=>void){if(busy||result||submitLock.current)return;action();playFeedback("selection");}
function renderAnswers(){
if(type==="multi_select")return<View style={{gap:9}}>{requiredSelections&&!result?<Text accessibilityLiveRegion="polite" style={{color:multi.length === requiredSelections?colors.green:colors.muted,fontSize:13,lineHeight:19,...typography.bodyMedium}}>Choose exactly {requiredSelections} · {multi.length}/{requiredSelections} selected{multi.length === requiredSelections?". Deselect an answer to change your choices.":""}</Text>:null}{challenge.options.map((option,optionIndex)=>{const active=multi.includes(optionIndex),right=Boolean(result)&&correctList.includes(optionIndex),wrong=Boolean(result)&&active&&!right;return<Choice key={optionIndex} role="checkbox" label={option} selected={active} correct={right} wrong={wrong} disabled={Boolean(result)||busy} prefix={active?"✓":""} onPress={()=>{if(!active&&requiredSelections&&multi.length>=requiredSelections)return;choose(()=>setMulti(current=>current.includes(optionIndex)?current.filter(value=>value!==optionIndex):[...current,optionIndex]));}}/>;})}</View>;
if(type==="ranking"){const remaining=challenge.options.map((option,optionIndex)=>({option,optionIndex})).filter(item=>!ranking.includes(item.optionIndex));return<View style={{gap:9}}>{!result?<><Body muted style={{fontSize:14,lineHeight:21}}>Tap each answer in your chosen order. Tap a numbered answer to remove it.</Body><Text accessibilityLiveRegion="polite" style={{color:colors.muted,fontSize:13,...typography.body}}>{ranking.length} of {challenge.options.length} placed</Text></>:<Eyebrow>Your order</Eyebrow>}{ranking.map((optionIndex,rankIndex)=><Choice key={`rank-${optionIndex}`} label={challenge.options[optionIndex]} accessibilityLabel={`${rankIndex+1}. ${challenge.options[optionIndex]}`} hint="Remove this answer from the order" prefix={String(rankIndex+1)} disabled={Boolean(result)||busy} onPress={()=>choose(()=>setRanking(current=>current.filter(value=>value!==optionIndex)))}/>)}{!result?remaining.map(({option,optionIndex})=><Choice key={optionIndex} label={option} hint={`Add as number ${ranking.length+1}`} prefix="+" disabled={busy} onPress={()=>choose(()=>setRanking(current=>[...current,optionIndex]))}/>):null}{result?<EditorialPanel><Eyebrow>Best order</Eyebrow>{correctList.map((optionIndex,rankIndex)=><Body key={`${optionIndex}-${rankIndex}`}>{rankIndex+1}. {challenge.options[optionIndex]}</Body>)}</EditorialPanel>:null}</View>;}
if(type==="classification")return<View style={{gap:10}}>{challenge.options.map((option,optionIndex)=><EditorialPanel key={optionIndex}><Body>{option}</Body>{result?<Text style={{color:colors.green,fontSize:13.5,lineHeight:20,...typography.bodyMedium}}>Best group: {categories.find(category=>category.id===correctGroups[String(optionIndex)])?.label??"See the explanation"}</Text>:null}<View accessibilityRole="radiogroup" accessibilityLabel={option} style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{categories.map(category=>{const active=classification[String(optionIndex)]===category.id,right=Boolean(result)&&correctGroups[String(optionIndex)]===category.id;return<Pressable accessibilityRole="radio" accessibilityLabel={`${option}: ${category.label}`} accessibilityState={{checked:active,disabled:Boolean(result)||busy}} key={category.id} disabled={Boolean(result)||busy} onPress={()=>choose(()=>setClassification(current=>({...current,[String(optionIndex)]:category.id})))} style={{minHeight:48,justifyContent:"center",paddingHorizontal:13,borderRadius:999,borderWidth:1,borderColor:right?colors.green:active?colors.cyan:colors.line,backgroundColor:right?"rgba(38,101,85,.22)":active?"rgba(32,79,114,.42)":"rgba(10,27,50,.65)"}}><Text style={{color:colors.text,fontSize:13.5,...typography.label}}>{category.label}</Text></Pressable>;})}</View></EditorialPanel>)}</View>;
return<View accessibilityRole="radiogroup" accessibilityLabel="Your answer" style={{gap:9}}>{challenge.options.map((option,optionIndex)=>{const right=Boolean(result)&&result?.correctIndex===optionIndex,wrong=Boolean(result)&&selected===optionIndex&&!right;return<Choice key={optionIndex} role="radio" label={option} selected={selected===optionIndex} correct={right} wrong={wrong} disabled={Boolean(result)||busy} prefix={String.fromCharCode(65+optionIndex)} onPress={()=>choose(()=>setSelected(optionIndex))}/>;})}</View>;
}
if(showSummary)return<Screen><LinearGradient colors={["rgba(32,81,108,.86)","rgba(36,42,89,.90)"]} style={{borderRadius:radius.xl,padding:20,gap:10,borderWidth:1,borderColor:"rgba(109,235,255,.25)"}}><Eyebrow>{mode==="diagnostic"?"Starting check complete":"Practice complete"}</Eyebrow><Title size={30}>Take one idea with you.</Title><Body>{answered.size} of {challenges.length} answers saved. A useful next step is to notice where this thinking applies today.</Body></LinearGradient><DeviceToolsNotice/><Eyebrow>Takeaways from this visit</Eyebrow>{visitIdeas.slice(-3).map(idea=><EditorialPanel key={idea.id}><Title size={21}>{idea.title}</Title><Body>{idea.principle}</Body><SaveIdeaButton idea={idea}/></EditorialPanel>)}<Body muted style={{fontSize:13,lineHeight:20}}>Showing up to three ideas from answers submitted in this visit. Saved ideas are available in your thinking toolkit.</Body><Body muted>Progress comes from understanding the reasoning, not chasing a perfect score.</Body>{error?<Text accessibilityLiveRegion="assertive" style={{color:colors.danger}}>{error}</Text>:null}<PrimaryButton label={mode==="practice"?"Back to skills":"Back to training"} trailingArrow loading={advancing} onPress={()=>void finish()}/></Screen>;
const score=result?.scoreFraction??(result?.correct?1:0);const skillName=challenge.scenario_category??challenge.challenge_type??challenge.title;
return<Screen ref={scrollRef}>
<View style={{gap:10}}><View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12}}><View style={{flexDirection:"row",alignItems:"center",gap:9,flex:1}}><SkillMotif kind={motifForSkill(skillName)} size={34}/><View style={{flex:1}}><Eyebrow>{modeLabel??(mode==="diagnostic"?"Starting check":mode==="practice"?"Skill practice":"Daily practice")}</Eyebrow></View></View><Text style={{color:colors.muted,fontSize:13.5,...typography.label,fontVariant:["tabular-nums"]}}>{Math.min(index+1,challenges.length)} of {challenges.length}</Text></View><ProgressBar value={progress}/></View>
<View style={{gap:9}}>{challenge.scenario_context?<Text style={{color:colors.muted,fontSize:14,lineHeight:21,...typography.body}}>{challenge.scenario_context}</Text>:null}<View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10}}><Eyebrow>{formatLabels[type]??"Question"}</Eyebrow><Text style={{color:colors.purple,fontSize:12.5,...typography.label}}>{difficulty(challenge.difficulty)}</Text></View><Title size={27}>{challenge.title}</Title><Body style={{fontSize:16.5,lineHeight:25}}>{challenge.prompt}</Body></View>
{renderAnswers()}
{challenge.confidence_required&&!result?<View style={{gap:10,paddingTop:2}}><View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8}}><Text style={{color:colors.text,fontSize:15.5,...typography.heading}}>How sure are you?</Text><Text style={{color:confidence===null?colors.muted:colors.cyan,fontSize:13.5,...typography.label}}>{confidence===null?"Choose one":`${confidence}%`}</Text></View><View accessibilityRole="radiogroup" accessibilityLabel="How sure are you?" style={{flexDirection:"row",gap:7}}>{[40,60,80,100].map(value=><Pressable accessibilityRole="radio" accessibilityLabel={`${value} percent confident`} accessibilityState={{checked:confidence===value,disabled:busy}} disabled={busy} key={value} onPress={()=>choose(()=>setConfidence(value))} style={({pressed})=>({flex:1,minHeight:48,borderRadius:999,borderWidth:1,borderColor:confidence===value?colors.cyan:colors.line,backgroundColor:confidence===value?"rgba(36,91,129,.45)":"rgba(13,29,54,.66)",alignItems:"center",justifyContent:"center",opacity:pressed?.78:1})}><Text style={{color:colors.text,fontSize:13,...typography.label}}>{value}%</Text></Pressable>)}</View><Body muted style={{fontSize:12.5,lineHeight:18}}>Confidence helps you notice when certainty and evidence diverge.</Body></View>:null}
{error?<Text accessibilityLiveRegion="assertive" selectable style={{color:colors.danger,fontSize:14.5,lineHeight:22,...typography.body}}>{error}</Text>:null}{!result&&answerReady&&challenge.confidence_required&&confidence===null?<Body muted>Choose your confidence above to submit.</Body>:null}
{!result?<PrimaryButton label={busy?"Checking…":type==="ranking"?"Use this order":type==="classification"?"Check my groups":type==="multi_select"?"Submit answers":"Submit answer"} onPress={()=>void submit()} disabled={!ready} loading={busy} trailingArrow/>:<View onLayout={event=>{if(resultScrollChallengeRef.current===challenge.id)return;resultScrollChallengeRef.current=challenge.id;scrollRef.current?.scrollTo({y:Math.max(0,event.nativeEvent.layout.y-12),animated:!reduced});}} style={{gap:12}}>
<LinearGradient colors={result.correct?["rgba(27,92,78,.92)","rgba(14,56,67,.94)"]:score>=.5?["rgba(83,69,61,.90)","rgba(38,44,68,.94)"]:["rgba(74,45,70,.90)","rgba(33,36,65,.95)"]} style={{borderRadius:radius.lg,borderWidth:1,borderColor:result.correct?"rgba(126,230,185,.38)":score>=.5?"rgba(255,209,147,.30)":"rgba(255,170,200,.28)",padding:17,gap:10}}><View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12}}><View style={{flex:1,gap:3}}><Eyebrow style={{color:result.correct?colors.green:score>=.5?colors.amber:colors.pink}}>{result.correct?"Great choice":score>=.5?"Partly right":"Worth reviewing"}</Eyebrow><Title size={24}>{result.correct?"Strong reasoning":score>=.5?"Good progress":"Review the reasoning"}</Title></View><View style={{paddingHorizontal:11,paddingVertical:7,borderRadius:999,backgroundColor:"rgba(7,16,34,.30)"}}><Text style={{color:colors.cyan,fontSize:14,...typography.metric}}>+{result.xpEarned} XP</Text></View></View><Body>{result.explanation}</Body></LinearGradient>
{result.skillUpdates?.length?<EditorialPanel><Eyebrow>Skill progress</Eyebrow>{result.skillUpdates.map(update=><View key={update.slug} style={{flexDirection:"row",justifyContent:"space-between",gap:14}}><Text style={{flex:1,color:colors.text,fontSize:15.5,lineHeight:22,...typography.bodyMedium}}>{(update.name??update.slug).replace(/^./,c=>c.toUpperCase())}</Text><Text style={{color:Number(update.delta??0)>=0?colors.green:colors.danger,fontSize:15.5,...typography.metric}}>{Number(update.delta??0)>=0?"+":""}{Number(update.delta??0).toFixed(1)}</Text></View>)}</EditorialPanel>:null}
<EditorialPanel><View style={{flexDirection:"row",alignItems:"center",gap:9}}><CogniIcon name="bookmark" size={22} color={colors.cyan}/><Eyebrow>Key idea</Eyebrow></View><Body>{result.thinkingPrinciple}</Body><SaveIdeaButton idea={{id:challenge.id,title:challenge.title,principle:result.thinkingPrinciple,application:result.application}}/></EditorialPanel><DeviceToolsNotice/><EditorialPanel><Eyebrow>Why this matters with AI</Eyebrow><Body>{result.application}</Body></EditorialPanel><PrimaryButton label={answered.size>=challenges.length?"Finish training":"Next question"} loading={advancing} trailingArrow onPress={()=>void next()}/>
</View>}
</Screen>;
}
