-- Cogni v0.12: plain-language refresh.
-- Changes learner-facing wording only. Slugs, scoring, answer indexes and learner history are preserved.

update public.skills set name='Checking AI answers', description='Check important AI-generated claims before relying on them.' where slug='ai-output-verification';
update public.skills set name='Asking better questions', description='Ask questions that are most likely to change what you do next.' where slug='better-questions';
update public.skills set name='Spotting assumptions', description='Notice what must be true for a plan, forecast or recommendation to work.' where slug='assumption-identification';
update public.skills set name='Spotting thinking biases', description='Notice common thinking patterns that can distort judgement.' where slug='bias-recognition';
update public.skills set name='Comparing different arguments', description='Compare different views using the same evidence and standards.' where slug='argument-comparison';
update public.skills set name='Correlation vs cause and effect', description='Tell the difference between a pattern and evidence that one thing caused another.' where slug='correlation-causation';
update public.skills set name='Critical thinking', description='Question claims, evidence and assumptions before accepting a conclusion.' where slug='critical-thinking';
update public.skills set name='Making decisions with uncertainty', description='Make sensible choices when you do not have all the information.' where slug='decision-uncertainty';
update public.skills set name='Judging evidence', description='Decide whether evidence is relevant, reliable and strong enough for the claim.' where slug='evidence-evaluation';
update public.skills set name='Spotting made-up AI claims', description='Notice when AI may have invented or overstated a fact, source or quotation.' where slug='hallucination-detection';
update public.skills set name='Spotting missing information', description='Find the missing fact that could change a decision.' where slug='missing-information';
update public.skills set name='Knowing when not to trust AI', description='Know when a person must check or approve an AI-assisted decision.' where slug='ai-trust-boundaries';
update public.skills set name='Logical reasoning', description='Check whether the facts and assumptions really support the conclusion.' where slug='logical-reasoning';
update public.skills set name='Defining the right problem', description='Make sure you are solving the real problem before choosing a solution.' where slug='problem-framing';
update public.skills set name='Checking source quality', description='Check where information came from, how current it is and whether it can be trusted.' where slug='source-quality';

with skill_objective(slug,objective) as (values
 ('critical-thinking','test the claim before deciding'),('ai-output-verification','check the AI answer before using it'),('evidence-evaluation','judge whether the evidence is strong enough'),('logical-reasoning','check whether the reasoning really supports the conclusion'),('bias-recognition','reduce the risk of bias'),('decision-uncertainty','make a sensible decision with incomplete information'),('problem-framing','define the real problem before choosing a solution'),('assumption-identification','spot the assumptions the recommendation depends on'),('correlation-causation','avoid mistaking a pattern for cause and effect'),('source-quality','decide whether the source is trustworthy enough'),('hallucination-detection','check whether a specific claim may be made up or unsupported'),('missing-information','find the missing fact that could change the decision'),('argument-comparison','compare the options fairly'),('better-questions','ask the question most likely to change what you do next'),('ai-trust-boundaries','decide where human review is still needed')
), proposed as (
 select c.id, regexp_replace(c.prompt,'\s+(Which response most directly tests the weakest point in|If you could take only one step before acting, which would most improve|Which response best protects|Classify each response by whether it strengthens or weakens|Rank these responses from strongest to weakest for|Select the TWO responses that would most improve|Which response most directly improves).*$','','i') || ' ' || case c.interaction_type when 'multi_select' then 'Choose the TWO actions that would best help you '||o.objective||'.' when 'ranking' then 'Put the responses in order from most to least useful for helping you '||o.objective||'.' when 'classification' then 'Sort each response by whether it helps or hurts your ability to '||o.objective||'.' when 'triage' then 'What would you do next to '||o.objective||'?' else 'What should you do first to '||o.objective||'?' end as new_prompt
 from public.challenges c join lateral (select s.slug from public.challenge_skill_mapping m join public.skills s on s.id=m.skill_id where m.challenge_id=c.id order by m.weight desc nulls last limit 1) ps on true join skill_objective o on o.slug=ps.slug
 where c.is_published=true and c.prompt ~* '(Which response most directly tests the weakest point in|If you could take only one step before acting, which would most improve|Which response best protects|Classify each response by whether it strengthens or weakens|Rank these responses from strongest to weakest for|Select the TWO responses that would most improve|Which response most directly improves)'
)
update public.challenges c set prompt=p.new_prompt,updated_at=now() from proposed p where c.id=p.id;

update public.challenges c set options=(select jsonb_agg(to_jsonb(case x.value
 when 'Accept the conclusion if the premises sound individually plausible.' then 'Accept the conclusion because each starting statement sounds plausible.'
 when 'Compare options using probabilities, downside, reversibility, and the value of waiting for more information.' then 'Compare how likely each outcome is, the downside, how easy the decision is to undo, and whether waiting for more information would help.'
 when 'Rewrite the argument as explicit premises and a conclusion, then test whether the conclusion actually follows.' then 'Write out the starting facts and the conclusion, then check whether the facts really support it.'
 when 'Treat the relationship as an association until alternative causes and confounders are tested.' then 'Treat it as a pattern until you have tested other possible causes.'
 when 'Actively seek evidence that would falsify the preferred conclusion.' then 'Actively look for evidence that could show your preferred conclusion is wrong.'
 when 'Check provenance, date, methodology, conflicts of interest, and whether the source can support the claim.' then 'Check where the information came from, when it was produced, how it was produced, possible conflicts of interest, and whether it supports the claim.'
 when 'Look for a counterexample that makes the premises true but the conclusion false.' then 'Look for a case where the starting facts are true but the conclusion is still wrong.'
 when 'Apply the same evidence, assumption, downside and reversibility criteria to both options.' then 'Judge both options using the same evidence, assumptions, downside and how easy each choice is to undo.'
 when 'a board-grade analysis with provenance, sensitivity ranges and accountable owners' then 'a board-ready analysis that shows sources, realistic ranges and who is accountable'
 when 'As a lead that needs independent corroboration' then 'As a lead that must be checked with another reliable source'
 when 'Prestige is an imperfect proxy and may encode authority/halo bias.' then 'Prestige is only a rough stand-in for quality and can make us give too much weight to status.'
 when 'Survivorship bias' then 'Survivorship bias — looking only at the visible winners'
 when 'Use base rates and broader incident data, not vividness alone.' then 'Use what usually happens in similar cases and the wider incident data, not just the most memorable example.' else x.value end) order by x.ord) from jsonb_array_elements_text(c.options) with ordinality x(value,ord)),updated_at=now()
where c.is_published=true and exists(select 1 from jsonb_array_elements_text(c.options) x(value) where x.value in ('Accept the conclusion if the premises sound individually plausible.','Compare options using probabilities, downside, reversibility, and the value of waiting for more information.','Rewrite the argument as explicit premises and a conclusion, then test whether the conclusion actually follows.','Treat the relationship as an association until alternative causes and confounders are tested.','Actively seek evidence that would falsify the preferred conclusion.','Check provenance, date, methodology, conflicts of interest, and whether the source can support the claim.','Look for a counterexample that makes the premises true but the conclusion false.','Apply the same evidence, assumption, downside and reversibility criteria to both options.','a board-grade analysis with provenance, sensitivity ranges and accountable owners','As a lead that needs independent corroboration','Prestige is an imperfect proxy and may encode authority/halo bias.','Survivorship bias','Use base rates and broader incident data, not vividness alone.'));

update public.challenge_answer_keys set thinking_principle='A confident AI answer still needs checking when the facts matter.' where thinking_principle='AI confidence and precision are not substitutes for external verification.';
update public.challenge_answer_keys set thinking_principle='Ask the question whose answer is most likely to change what you do.' where thinking_principle='Choose questions by how much their answers could change the action.';
update public.challenge_answer_keys set thinking_principle='Judge both sides using the same standards.' where thinking_principle='Compare arguments on shared criteria, not presentation strength or status.';
update public.challenge_answer_keys set thinking_principle='A pattern does not prove that one thing caused the other.' where thinking_principle='Correlation is a clue, not a causal verdict.';
update public.challenge_answer_keys set thinking_principle='Use AI more freely for low-risk tasks; keep human review for decisions that matter.' where thinking_principle='Delegate low-risk cognition; retain human accountability for consequential judgement.';
update public.challenge_answer_keys set thinking_principle='Build checks into the process so your preferred answer has to survive challenge.' where thinking_principle='Design the process so the preferred answer has to survive challenge.';
update public.challenge_answer_keys set thinking_principle='Make the key assumptions visible before trusting the forecast or recommendation.' where thinking_principle='Expose dependencies before debating the final number.';
update public.challenge_answer_keys set thinking_principle='Define the problem before deciding on the solution.' where thinking_principle='Frame the problem independently of the preferred solution.';
update public.challenge_answer_keys set thinking_principle='Judge a source by where the evidence came from and whether it fits the claim.' where thinking_principle='Judge the source by how the evidence was produced and whether it fits the claim.';
update public.challenge_answer_keys set thinking_principle='Be clear about what you know, what you do not know, and what would change your decision.' where thinking_principle='Manage uncertainty explicitly instead of hiding it inside a single forecast.';
update public.challenge_answer_keys set thinking_principle='Use evidence that directly tests the claim you need to judge.' where thinking_principle='Match the evidence design to the claim you need to evaluate.';
update public.challenge_answer_keys set thinking_principle='Focus on the missing information most likely to change the decision.' where thinking_principle='Prioritise information by its expected impact on the choice.';
update public.challenge_answer_keys set thinking_principle='Separate the claim, the evidence and other possible explanations before deciding.' where thinking_principle='Separate claim, evidence and alternatives before committing.';
update public.challenge_answer_keys set thinking_principle='The more specific a claim is, the more important it is to check it.' where thinking_principle='Specificity increases the need for verification, not trust.';
update public.challenge_answer_keys set thinking_principle='Ask whether the starting facts really support the conclusion.' where thinking_principle='Test validity by asking whether the premises could be true while the conclusion is false.';

update public.challenge_answer_keys set application='AI can reinforce the viewpoint in your prompt. Ask for evidence against your preferred answer and for other ways to frame the problem.' where application like 'AI can amplify your framing and confirmation bias%';
update public.challenge_answer_keys set application='AI can make weak reasoning sound convincing. Break the reasoning into steps and check each one.' where application like 'AI can generate persuasive chains of reasoning%';
update public.challenge_answer_keys set application='AI can make weak sources sound authoritative. Open the original source and check that it is current and relevant.' where application like 'AI often compresses source quality%';
update public.challenge_answer_keys set application='Ask AI to separate facts, assumptions and forecasts. Then check the assumptions that matter most.' where application like 'Ask AI to label facts, assumptions and forecasts%';
update public.challenge_answer_keys set application='Ask AI to make the strongest case for both sides, then judge both using the same evidence standard.' where application like 'Ask AI to steelman both sides%';
update public.challenge_answer_keys set application='Ask AI which missing fact could most change its recommendation, then verify that fact.' where application like 'Ask AI what missing fact%';
update public.challenge_answer_keys set application='Tell AI the outcome you want and the constraints before asking for solutions.' where application like 'Before asking AI for solutions%';
update public.challenge_answer_keys set application='Set clear rules for when AI can act, when a person must review, and what must be checked.' where application like 'Design AI workflows with explicit escalation%';
update public.challenge_answer_keys set application='Use AI to speed up analysis, but check important facts and keep a person responsible for the final decision.' where application like 'For consequential work%';
update public.challenge_answer_keys set application='Treat exact but unsupported AI claims as a reason to verify, especially when the stakes are high.' where application like 'Treat unsupported AI specificity%';
update public.challenge_answer_keys set application='Use AI scenarios as possibilities, not facts. Compare realistic ranges, serious downsides and what would make you change course.' where application like 'Use AI scenarios as inputs%';
update public.challenge_answer_keys set application='Use AI to suggest questions, then choose the one that tests the most important assumption.' where application like 'Use AI to generate candidate questions%';
update public.challenge_answer_keys set application='With AI output, smooth writing is not proof. Identify the claim and check what evidence could show it is wrong.' where application like 'Use the same discipline with AI output%';
update public.challenge_answer_keys set application='When AI summarises evidence, check the sample, method and comparison behind the summary.' where application like 'When AI summarises evidence%';
update public.challenge_answer_keys set application='When AI gives a cause-and-effect story, ask what other factor could explain the pattern and what evidence would separate the explanations.' where application like 'When AI supplies a causal story%';

update public.challenge_answer_keys k set explanation=replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(explanation,'falsifiable','able to be tested and shown wrong'),'confounders','other factors that could explain the pattern'),'confounder','other factor that could explain the pattern'),'counterfactual','what would have happened otherwise'),'provenance','where the information came from'),'reversibility','how easy it is to undo'),'base rates','what usually happens in similar cases'),'second-order','knock-on'),'third-order','further knock-on'),'tail risks','unlikely but serious downsides') from public.challenges c where c.id=k.challenge_id and c.is_published=true;

update public.challenges set title=replace(replace(replace(replace(replace(replace(replace(replace(replace(title,'AI-output verification','Checking AI answers'),'Assumption identification','Spotting assumptions'),'Cognitive-bias recognition','Spotting thinking biases'),'Comparing competing arguments','Comparing different arguments'),'Correlation vs causation','Correlation vs cause and effect'),'Decision-making under uncertainty','Making decisions with uncertainty'),'Evidence evaluation','Judging evidence'),'Hallucination detection','Spotting made-up AI claims'),'Source-quality evaluation','Checking source quality') where is_published=true;
update public.daily_lessons set subtitle='A short lesson for your learning context' where is_published=true and subtitle='Audience-specific judgement practice';
update public.daily_lessons set title=replace(replace(replace(replace(replace(replace(replace(replace(replace(title,'AI-output verification','Checking AI answers'),'Assumption identification','Spotting assumptions'),'Cognitive-bias recognition','Spotting thinking biases'),'Comparing competing arguments','Comparing different arguments'),'Correlation vs causation','Correlation vs cause and effect'),'Decision-making under uncertainty','Making decisions with uncertainty'),'Evidence evaluation','Judging evidence'),'Hallucination detection','Spotting made-up AI claims'),'Source-quality evaluation','Checking source quality') where is_published=true;
update public.daily_lessons set content=replace(replace(replace(replace(replace(replace(replace(replace(content::text,'falsifiable','able to be tested and shown wrong'),'confounders','other factors that could explain the pattern'),'counterfactual','what would have happened otherwise'),'provenance','where the information came from'),'reversibility','how easy it is to undo'),'second-order','knock-on'),'third-order','further knock-on'),'premise','starting fact or assumption')::jsonb where is_published=true;

do $$ begin if exists(select 1 from public.challenges where is_published=true group by lower(regexp_replace(trim(prompt),'\s+',' ','g')) having count(*)>1) then raise exception 'Plain-language refresh would create duplicate published prompts'; end if; end $$;
