-- Cogni v0.14 — audience-depth personalisation foundation.
-- Safe for the normal one-time migration path; additive and history-preserving.

alter table public.profiles add column if not exists function_area text;
alter table public.profiles add column if not exists primary_goal text;
alter table public.profiles add column if not exists study_stage text;
alter table public.profiles add column if not exists role_focus text;
alter table public.profiles add column if not exists responsibility_scope text;
alter table public.profiles add column if not exists organisation_scale text;
alter table public.profiles add column if not exists context_updated_at timestamptz;

alter table public.challenges add column if not exists content_key text;
alter table public.challenges add column if not exists function_tags text[] not null default '{}'::text[];
alter table public.challenges add column if not exists industry_tags text[] not null default '{}'::text[];
alter table public.challenges add column if not exists goal_tags text[] not null default '{}'::text[];
alter table public.challenges add column if not exists scenario_category text;
alter table public.challenges add column if not exists complexity_level smallint;
alter table public.challenges add column if not exists diagnostic_role text;

alter table public.daily_lessons add column if not exists content_key text;
alter table public.daily_lessons add column if not exists function_tags text[] not null default '{}'::text[];
alter table public.daily_lessons add column if not exists industry_tags text[] not null default '{}'::text[];
alter table public.daily_lessons add column if not exists goal_tags text[] not null default '{}'::text[];
alter table public.daily_lessons add column if not exists scenario_category text;
alter table public.daily_lessons add column if not exists complexity_level smallint;

alter table public.session_feedback add column if not exists relevance_rating text;
alter table public.session_feedback add column if not exists relevance_reason text;
alter table public.session_feedback add column if not exists difficulty_feedback text;
alter table public.session_feedback add column if not exists function_area text;
alter table public.session_feedback add column if not exists industry text;
alter table public.session_feedback add column if not exists primary_goal text;

do $$ begin
  if not exists(select 1 from pg_constraint where conname='challenges_complexity_level_check') then
    alter table public.challenges add constraint challenges_complexity_level_check check (complexity_level is null or complexity_level between 1 and 6);
  end if;
  if not exists(select 1 from pg_constraint where conname='lessons_complexity_level_check') then
    alter table public.daily_lessons add constraint lessons_complexity_level_check check (complexity_level is null or complexity_level between 1 and 6);
  end if;
  if not exists(select 1 from pg_constraint where conname='challenges_diagnostic_role_check') then
    alter table public.challenges add constraint challenges_diagnostic_role_check check (diagnostic_role is null or diagnostic_role in ('core','audience_applied','legacy'));
  end if;
  if not exists(select 1 from pg_constraint where conname='session_feedback_relevance_check') then
    alter table public.session_feedback add constraint session_feedback_relevance_check check (relevance_rating is null or relevance_rating in ('very_relevant','mostly_relevant','not_very_relevant'));
  end if;
  if not exists(select 1 from pg_constraint where conname='session_feedback_relevance_reason_check') then
    alter table public.session_feedback add constraint session_feedback_relevance_reason_check check (relevance_reason is null or relevance_reason in ('wrong_context','too_basic','too_advanced','repetitive','other'));
  end if;
end $$;

create unique index if not exists idx_challenges_content_key on public.challenges(content_key) where content_key is not null;
create unique index if not exists idx_lessons_content_key on public.daily_lessons(content_key) where content_key is not null;
create index if not exists idx_challenges_function_tags on public.challenges using gin(function_tags);
create index if not exists idx_challenges_industry_tags on public.challenges using gin(industry_tags);
create index if not exists idx_challenges_goal_tags on public.challenges using gin(goal_tags);
create index if not exists idx_challenges_scenario_category on public.challenges(scenario_category);
create index if not exists idx_lessons_function_tags on public.daily_lessons using gin(function_tags);
create index if not exists idx_lessons_goal_tags on public.daily_lessons using gin(goal_tags);
create index if not exists idx_session_feedback_relevance on public.session_feedback(audience_segment,relevance_rating,created_at desc);

update public.challenges set diagnostic_role='legacy' where is_diagnostic=true and diagnostic_role is null;
update public.challenges set diagnostic_role='core' where id in (
 'a8eb6101-cd86-54b9-8c39-e3b3529b0543','70d0f45e-049e-5b90-893d-f5b01b7062df','f3792488-af8e-5c15-9317-76faf4a0ed1c','44cc94db-e95b-5059-8dad-5d40a1656a9c','644994f6-c5e9-58bb-a3f1-08025bb9b535','91a48c5c-dfa8-5a4e-b46e-fefcaf4a1194','ef14e7eb-36fa-581c-976f-4128c2496db7'
);

update public.challenges set complexity_level=case when difficulty<=45 then 1 when difficulty<=52 then 2 when difficulty<=59 then 3 when difficulty<=66 then 4 when difficulty<=73 then 5 else 6 end where complexity_level is null;
update public.daily_lessons set complexity_level=case when difficulty<=45 then 1 when difficulty<=52 then 2 when difficulty<=59 then 3 when difficulty<=66 then 4 when difficulty<=73 then 5 else 6 end where complexity_level is null;
update public.challenges set scenario_category=nullif(trim(regexp_replace(coalesce(scenario_context,title),'^.*?•\s*','','i')),'') where scenario_category is null;
update public.daily_lessons set scenario_category=nullif(trim(regexp_replace(coalesce(scenario_context,title),'^.*?•\s*','','i')),'') where scenario_category is null;
update public.daily_lessons set subtitle=left(content->>'principle',90) where is_published=true and subtitle='A short lesson for your learning context' and nullif(content->>'principle','') is not null;

create temporary table tmp_v014_diag(
 content_key text,audience text,title text,prompt text,options jsonb,correct_index int,difficulty int,
 scenario_context text,scenario_category text,skill_slug text,explanation text,principle text,application text,
 function_tags text[],goal_tags text[],complexity_level smallint
) on commit drop;

insert into tmp_v014_diag values
('diag_uni_evidence','university_student','The citation in your essay','An AI draft gives you a statistic from a “2025 Oxford study”, but you cannot find the paper. What is the strongest next step?','["Use the statistic because the university name sounds credible","Search for the original study and verify that it exists and supports the claim","Replace Oxford with a less specific source name","Keep it if the AI gives the same citation twice"]',1,44,'University • AI-assisted essay','academic evidence','evidence-evaluation','A credible-sounding citation is not evidence until you can trace and check the original source.','Trace important claims back to the source that actually produced the evidence.','This protects assessed work from confident AI citations that may be incomplete or invented.',array['study_research'],array['academic_performance','work_effectively_with_ai'],2),
('diag_uni_assumption','university_student','The group-project survey','Your group says students clearly prefer its proposal because 82% of a WhatsApp poll supported it. What assumption most needs checking?','["That 82 is a large number","That the people who answered are representative of the students the proposal is meant for","That WhatsApp can display percentages correctly","That students understand what a group project is"]',1,45,'University • Group project','group work','assumption-identification','The conclusion depends on the respondents being representative, not merely on the percentage being high.','Make the hidden condition carrying the conclusion visible.','The same move helps you challenge surveys, AI summaries and group claims without being argumentative.',array['study_research'],array['academic_performance','critical_thinking_general'],2),
('diag_uni_cause','university_student','Did the study tool cause the marks?','Students who use an AI revision tool get higher marks on average. Which conclusion is justified by that fact alone?','["The tool caused the higher marks","The tool probably caused the marks because AI is efficient","The two are associated, but other differences between the students could explain the result","Students who do not use AI are less motivated"]',2,46,'University • Exam preparation','study tools','correlation-causation','Students who choose the tool may differ in motivation, prior attainment or study time, so the pattern alone does not establish cause.','A pattern is a clue; test other explanations before calling it a cause.','This helps when interpreting studies, social-media claims and AI-generated explanations of data.',array['study_research'],array['academic_performance','critical_thinking_general'],2),
('diag_uni_ai','university_student','The perfect quotation','An AI study assistant gives you an exact quotation and page number from a book you cannot access. What should you do?','["Use it because exact page numbers make fabrication unlikely","Ask the AI to make the quotation longer","Verify the quotation in the original book or a reliable copy before using it","Paraphrase it so verification is no longer necessary"]',2,43,'University • AI study assistant','AI study','ai-output-verification','Specific detail can make an AI claim look trustworthy without making it true.','The more specific and consequential the AI claim, the more important it is to verify.','This reduces hallucination and academic-integrity risk when AI helps with research.',array['study_research'],array['work_effectively_with_ai','academic_performance'],2),
('diag_uni_uncertainty','university_student','Choosing a module','A friend says a module is “a disaster”, but their priorities are very different from yours and published feedback is mixed. What is the best decision approach?','["Avoid the module because a first-hand story is more useful than averages","Choose it because mixed feedback means the risk cancels out","Identify what matters to you, check several relevant sources and decide with the remaining uncertainty visible","Wait until someone can guarantee whether you will enjoy it"]',2,45,'University • Module choice','study choices','decision-uncertainty','Good decisions do not require certainty; they require relevant evidence, clear priorities and awareness of what remains unknown.','Make the best choice with the evidence available, then stay clear about what you still do not know.','This applies to modules, internships, finances and everyday choices where no source can remove all uncertainty.',array['study_research'],array['make_better_decisions'],2),

('diag_grad_evidence','graduate_early_career','The under-budget project','A dashboard says your project is 9% under budget halfway through, but several major invoices have not arrived. What should you do before reporting the saving?','["Report the 9% because the dashboard is the official source","Check committed costs and missing invoices before treating the variance as a saving","Round the saving down to 5% to be cautious","Wait until year end before discussing budget at all"]',1,49,'Graduate • Project dashboard','workplace analysis','evidence-evaluation','The headline number does not yet reflect important committed costs.','Ask whether the evidence measures the thing you are about to claim.','This is the judgement that stops an early-career analyst presenting a technically true but misleading number.',array['finance_commercial','operations'],array['analyse_information','build_professional_judgement'],2),
('diag_grad_assumption','graduate_early_career','The automation assumption','A manager says a process takes too long and concludes that an AI tool will fix it. Which assumption most needs checking before you act?','["That AI tools can produce polished output","That the delay is actually caused by work an AI tool can remove rather than approvals, rework, hand-offs or unclear ownership","That the manager has used AI before","That the process has a written name"]',1,50,'Graduate • Vague stakeholder request','assumption in a request','assumption-identification','The proposed solution only helps if the real cause of the delay is work the tool can remove. The manager’s request contains that assumption implicitly.','Make the assumption carrying the proposed solution visible before acting on it.','This helps you respond intelligently to senior requests without either blindly executing them or resisting them.',array['general_professional'],array['build_professional_judgement','progress_faster'],2),
('diag_grad_cause','graduate_early_career','Did the campaign work?','Customer sign-ups rose after a new campaign launched, but a price promotion started on the same day. What is the strongest conclusion?','["The campaign caused the increase because it happened first","The promotion caused the increase because price always matters most","The increase is encouraging, but the data does not yet separate the effect of the campaign from the promotion","Both caused exactly half of the increase"]',2,50,'Graduate • Performance data','dashboard interpretation','correlation-causation','Two changes happened together, so the result does not identify which one caused the outcome.','When several things change at once, look for evidence that separates their effects.','This prevents you sounding more certain than the evidence allows in meetings and presentations.',array['marketing','sales_client'],array['analyse_information','communicate_with_confidence'],2),
('diag_grad_ai','graduate_early_career','The AI market statistic','AI gives you a market statistic for a presentation to your manager, but the cited page does not contain the number. What is the strongest next step?','["Use it because the AI supplied a specific source","Round the number so it looks less precise","Trace the statistic to a source that actually supports it before putting it in the presentation","Ask the AI to generate a second citation"]',2,48,'Graduate • Manager presentation','AI-assisted analysis','ai-output-verification','A citation is not verification when the cited source does not contain the claim.','Check important AI-generated facts against the source that actually supports them.','This stops polished AI research becoming unsupported evidence in an early-career presentation.',array['general_professional'],array['work_effectively_with_ai','communicate_with_confidence'],2),
('diag_grad_uncertainty','graduate_early_career','Should you escalate?','You spot a possible reporting error an hour before a senior meeting. You are not yet sure it is material. What is the strongest response?','["Say nothing until you can prove the error completely","Quietly delete the suspicious number","Flag the uncertainty early, explain what you know and what you are checking, and avoid overstating it","Tell everyone the report is wrong so nobody relies on it"]',2,51,'Graduate • Risk escalation','speaking up','decision-uncertainty','Good escalation separates facts from uncertainty and makes the next check clear.','Communicate uncertainty without either hiding it or exaggerating it.','This is a core early-career credibility skill: senior people can trust you to surface risk proportionately.',array['general_professional'],array['communicate_with_confidence','build_professional_judgement'],3),

('diag_junior_evidence','junior_professional','The confident recommendation','You are asked to recommend one of two options. One has stronger headline benefits, but its evidence comes from a small pilot run by the vendor selling it. What matters most before you recommend it?','["Whether the vendor presentation is visually clear","Whether the pilot evidence is independent enough, representative enough and relevant to your decision","Whether the option has the more ambitious benefit number","Whether senior stakeholders already prefer it"]',1,56,'Junior professional • Recommendation','recommendation quality','evidence-evaluation','Evidence quality matters more than the confidence or ambition of the recommendation.','Judge whether the evidence is strong enough for the claim you need to make.','This is how a professional becomes trusted for judgement rather than just producing analysis.',array['general_professional'],array['make_recommendations','build_professional_judgement'],3),
('diag_junior_assumption','junior_professional','The architecture shortcut','A technical proposal assumes a new platform will cut support effort by 30% because it is more automated. Which assumption deserves the most attention?','["That automation always uses modern technology","That the current support workload is actually caused by tasks the new platform will remove rather than integration, data or user issues","That 30 is a round number","That support teams prefer fewer tickets"]',1,57,'Junior professional • Architecture recommendation','technical trade-off','assumption-identification','The claimed benefit depends on the new platform addressing the actual drivers of support effort.','Find the assumption that carries the benefit case, not the assumption that is easiest to debate.','This applies to technical, commercial, HR and operational recommendations alike.',array['technology_engineering'],array['make_recommendations','build_professional_judgement'],3),
('diag_junior_cause','junior_professional','The engagement improvement','Employee engagement rose after a new manager joined, but pay changes and a workload reduction happened in the same quarter. What should you conclude?','["The manager caused the improvement","The pay change caused it because money is the strongest incentive","The result is positive, but several plausible causes changed together and need separating","The workload reduction had no effect because it was temporary"]',2,56,'Junior professional • People analysis','people evidence','correlation-causation','The timing is consistent with several explanations, not one proven cause.','When outcomes improve after several changes, test competing explanations before crediting one intervention.','This helps you defend analysis under challenge instead of relying on a convenient story.',array['people_hr'],array['analyse_information','build_professional_judgement'],3),
('diag_junior_ai','junior_professional','The AI vendor comparison','AI ranks a supplier first and cites three market benchmarks, but none of the benchmarks can be traced to an original source. What should you do?','["Use the ranking but remove the citations","Verify the important benchmarks and reconstruct the recommendation from traceable evidence before relying on it","Ask the AI to add more benchmarks","Choose the second-ranked supplier to avoid AI bias"]',1,55,'Junior professional • Supplier analysis','AI-assisted recommendation','ai-output-verification','A recommendation is only as auditable as the evidence carrying it.','Use AI to accelerate analysis, not to bypass verification of decision-critical facts.','This protects the professional credibility of recommendations that senior stakeholders may act on.',array['finance_commercial'],array['work_effectively_with_ai','make_recommendations'],3),
('diag_junior_uncertainty','junior_professional','Recommendation before the deadline','You must make a recommendation today, but one important data point will not be available until next week. What is the strongest approach?','["Delay the decision automatically because incomplete data makes judgement impossible","Pick the most popular option and omit the missing data","Show the current recommendation, state how the missing fact could change it, and propose a reversible next step where possible","Give equal weight to every option because uncertainty is high"]',2,58,'Junior professional • Time-pressured recommendation','decision under incomplete information','decision-uncertainty','Professional judgement means making the best defensible decision while showing what could change it.','Make uncertainty decision-useful by linking it to consequences and next steps.','This is how you manage upwards without pretending to know more than you do.',array['general_professional'],array['make_recommendations','communicate_with_confidence'],3),

('diag_mgr_evidence','management','Conflicting performance evidence','A strong performer misses two deadlines. Their manager says it shows poor ownership; project colleagues say priorities changed without warning. What should you do first?','["Back the line manager because they are accountable","Treat the missed deadlines as objective proof of underperformance","Reconstruct the agreed priorities, changes and evidence from both sides before deciding what the behaviour means","Average the two views and give a neutral rating"]',2,63,'Management • Performance decision','people judgement','evidence-evaluation','The same outcome can reflect performance, priorities, dependencies or management choices.','Separate the observed outcome from the explanation attached to it.','This supports fairer performance decisions and better coaching conversations.',array['people_hr'],array['people_decisions','managing_risk'],4),
('diag_mgr_assumption','management','The capacity plan','A team is at 95% utilisation and a plan assumes that means there is room to take on one more priority if everyone “stays focused”. What assumption is most fragile?','["That 95 is less than 100","That high utilisation leaves enough slack for variability, rework, learning and unexpected work","That people understand percentages","That priorities should have owners"]',1,64,'Management • Team capacity','capacity and prioritisation','assumption-identification','Near-full utilisation often removes the slack needed to absorb variation and can increase delays and rework.','Test the operating assumption behind the plan, not just the arithmetic.','This helps managers make clearer choices about what not to do, not just how to fit in more work.',array['operations','people_hr'],array['prioritisation','resource_allocation'],4),
('diag_mgr_cause','management','The productivity jump','Team output rises 18% after an AI assistant launches, while overtime also rises and the backlog is temporarily easier. What is the strongest conclusion?','["The AI created an 18% productivity gain","The overtime created all of the gain","The result is promising, but the evidence does not yet isolate AI impact from workload mix and extra hours","Productivity cannot be measured when AI is involved"]',2,65,'Management • AI productivity claim','team productivity','correlation-causation','A headline productivity change can combine technology effects, effort, mix and measurement choices.','Before scaling a management intervention, separate the intervention from other changes that can explain the result.','This reduces the risk of scaling an attractive story instead of a real improvement.',array['technology_engineering','people_hr'],array['ai_enabled_management','resource_allocation'],4),
('diag_mgr_ai','management','The AI performance summary','An AI summary labels an employee “low impact” because their measurable output is below peers, but it does not include mentoring, incident support or project complexity. What should you do?','["Use the label because consistent metrics improve fairness","Ask AI to rewrite the label more politely","Treat it as one input and review the missing context before making a people decision","Remove all quantitative evidence from performance reviews"]',2,63,'Management • Performance review','AI-assisted people decision','ai-output-verification','A consistent metric can still be incomplete, especially when it becomes a judgement about a person.','Important AI-generated judgements need human verification of the evidence and missing context.','This protects fairness while still allowing managers to benefit from AI-assisted analysis.',array['people_hr'],array['people_decisions','ai_enabled_management'],4),
('diag_mgr_uncertainty','management','Two priorities, one team','Two initiatives are both valuable, but the team can deliver only one properly this quarter. One has higher upside; the other avoids a serious operational risk. What is the strongest decision process?','["Choose the higher-upside initiative because growth should dominate","Choose the risk initiative because risk should always dominate","Compare consequence, likelihood, timing, strategic value and how easy it is to change course, then make the trade-off explicit to stakeholders","Ask the team to attempt both and review progress later"]',2,66,'Management • Competing priorities','resource allocation','decision-uncertainty','Management often means choosing between legitimate objectives rather than finding a perfect answer.','Make the trade-off explicit and use consistent criteria instead of hiding the conflict in an overloaded plan.','This is the judgement behind credible prioritisation, resource allocation and stakeholder management.',array['operations','strategy'],array['prioritisation','resource_allocation'],4),

('diag_exec_evidence','executive','The board investment paper','A board paper recommends entering a new market using an AI-generated market-size estimate that is repeated by several reports but traces back to the same consultancy model. What should receive the most scrutiny?','["Whether three reports use the same terminology","Whether the apparently independent sources actually rely on one underlying estimate and whether that estimate is fit for the decision","Whether the market estimate is rounded","Whether the board paper contains enough charts"]',1,69,'Executive • Market entry','strategic evidence','evidence-evaluation','Several citations can create false independence when they all inherit the same underlying estimate.','Trace strategic evidence to its origin and test whether apparently separate sources are genuinely independent.','This identifies the assumption or source that deserves board attention before capital is committed.',array['strategy'],array['strategy','capital_allocation'],5),
('diag_exec_assumption','executive','The growth strategy','A strategy case assumes a premium product can take share without reducing demand for the company’s existing offer. Which issue matters most?','["Whether the premium product has a memorable name","Whether growth is truly incremental or partly cannibalises existing revenue and margin","Whether the launch presentation is concise","Whether competitors will notice the launch"]',1,70,'Executive • Portfolio strategy','strategic trade-off','assumption-identification','The value case depends on where the growth comes from, not just on the new product’s standalone revenue.','Find the assumption carrying the strategic economics, including effects elsewhere in the system.','This is how executive judgement moves beyond headline upside to portfolio-level consequences.',array['strategy'],array['strategy','commercial_growth'],5),
('diag_exec_cause','executive','Did the transformation work?','Operating margin improves after a major transformation, but the same period includes price rises, a favourable market and a large restructuring. What is the strongest conclusion?','["The transformation caused the margin improvement because it finished first","The restructuring caused the improvement because cost actions are measurable","The result supports optimism, but attribution requires separating transformation effects from market, price and restructuring effects","Attribution is impossible in executive decisions, so the cause does not matter"]',2,70,'Executive • Transformation','strategic attribution','correlation-causation','Strategic outcomes rarely move for one reason, and attribution matters when deciding what to repeat or scale.','Separate the attractive narrative from the evidence about what actually drove the result.','This improves decisions about follow-on investment, accountability and future transformation design.',array['strategy'],array['transformation','organisational_performance'],5),
('diag_exec_ai','executive','The precise market-share claim','An AI-generated board briefing states a competitor has exactly 17.4% market share, but the cited source does not publish that figure. What is the best response?','["Use 17.4% because precision suggests a calculation was performed","Round it to 17% so it looks less certain","Verify how the figure was derived or remove it from the decision case until it can be supported","Ask the AI to provide a confidence percentage"]',2,68,'Executive • Board briefing','AI-assisted board material','ai-output-verification','Precision can hide unsupported inference just as easily as it can reflect good measurement.','Decision-critical AI claims must be traceable enough for accountable human review.','This keeps AI useful in executive preparation without letting polished specificity become board evidence.',array['strategy','technology_engineering'],array['ai_and_technology','governance_risk'],5),
('diag_exec_uncertainty','executive','The asymmetric investment','A new capability could create major strategic upside, but demand is uncertain. A small pilot would preserve the option to scale but delay some benefits. What is the strongest framing?','["Approve the full investment because strategic opportunities require conviction","Reject it because uncertainty makes the business case unreliable","Compare the value of learning and preserving options against the cost of delay, then choose the commitment level that fits the downside","Wait until demand can be forecast with high confidence"]',2,72,'Executive • Strategic investment','optionality and capital allocation','decision-uncertainty','When uncertainty is high, the size and ability to change the commitment can matter as much as expected upside.','Use staged commitment to buy information and preserve strategic options where that improves the risk-return shape.','This is executive decision quality under uncertainty: not indecision, and not false precision.',array['strategy'],array['capital_allocation','strategy'],5);

insert into public.challenges(id,content_key,title,prompt,options,challenge_type,difficulty,is_diagnostic,confidence_required,is_published,sort_order,interaction_type,interaction_config,audience_segments,scenario_context,scenario_category,function_tags,goal_tags,complexity_level,diagnostic_role)
select gen_random_uuid(),s.content_key,s.title,s.prompt,s.options,'scenario_mcq',s.difficulty,true,true,true,2000+row_number() over(order by s.audience,s.content_key),'single_choice','{}'::jsonb,array[s.audience],s.scenario_context,s.scenario_category,s.function_tags,s.goal_tags,s.complexity_level,'audience_applied'
from tmp_v014_diag s where not exists(select 1 from public.challenges c where c.content_key=s.content_key);

insert into public.challenge_answer_keys(challenge_id,correct_index,explanation,thinking_principle,application,error_patterns,correct_answer)
select c.id,s.correct_index,s.explanation,s.principle,s.application,'{}'::jsonb,to_jsonb(s.correct_index)
from tmp_v014_diag s join public.challenges c on c.content_key=s.content_key
where not exists(select 1 from public.challenge_answer_keys k where k.challenge_id=c.id);

insert into public.challenge_skill_mapping(challenge_id,skill_id,weight)
select c.id,sk.id,1.0 from tmp_v014_diag s join public.challenges c on c.content_key=s.content_key join public.skills sk on sk.slug=s.skill_slug
where not exists(select 1 from public.challenge_skill_mapping m where m.challenge_id=c.id and m.skill_id=sk.id);
