-- Cogni v0.14 — conservative metadata backfill for contextual matching.
-- Untagged content remains valid audience/universal fallback.

update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['technology_engineering'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(architecture|incident|technical|system|software|code|release|cyber|data breach|AI tool|technology|engineering)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['finance_commercial'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(budget|forecast|margin|supplier|procurement|contract|pricing|investment case|benefit|cost estimate|vendor renewal)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['marketing'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(campaign|brand|customer segment|churn|attribution|A/B|market research)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['people_hr'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(recruit|hiring|employee|performance review|engagement|people|succession|team morale|underperformance)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['operations'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(process|capacity|quality|schedule|workflow|productivity|operations|project recovery|rework)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['sales_client'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(sales|client|pipeline|proposal|customer communication)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['strategy'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(market entry|acquisition|M&A|portfolio|strategy|strategic|divest|capital allocation|board|transformation)';

update public.challenges set goal_tags=array(select distinct x from unnest(goal_tags||array['work_effectively_with_ai'])x) where is_published=true and (challenge_type='ai_answer_audit' or prompt ~* '\bAI\b');
update public.challenges c set goal_tags=array(select distinct x from unnest(c.goal_tags||array['analyse_information'])x) where exists(select 1 from public.challenge_skill_mapping m join public.skills s on s.id=m.skill_id where m.challenge_id=c.id and s.slug in ('evidence-evaluation','source-quality','correlation-causation','missing-information'));
update public.challenges c set goal_tags=array(select distinct x from unnest(c.goal_tags||array['make_better_decisions'])x) where exists(select 1 from public.challenge_skill_mapping m join public.skills s on s.id=m.skill_id where m.challenge_id=c.id and s.slug in ('decision-uncertainty','critical-thinking','assumption-identification','problem-framing'));
update public.challenges c set goal_tags=array(select distinct x from unnest(c.goal_tags||array['build_professional_judgement'])x) where exists(select 1 from public.challenge_skill_mapping m join public.skills s on s.id=m.skill_id where m.challenge_id=c.id and s.slug in ('better-questions','argument-comparison','logical-reasoning','ai-trust-boundaries'));

update public.daily_lessons set goal_tags=array(select distinct x from unnest(goal_tags||array['work_effectively_with_ai'])x) where is_published=true and (title||' '||content::text) ~* '\bAI\b';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['technology_engineering'])x) where is_published=true and (title||' '||content::text) ~* '(technology|system|software|AI|cyber|data)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['finance_commercial'])x) where is_published=true and (title||' '||content::text) ~* '(budget|forecast|investment|supplier|commercial|price|finance)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['people_hr'])x) where is_published=true and (title||' '||content::text) ~* '(employee|team|manager|hiring|performance|people)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['strategy'])x) where is_published=true and (title||' '||content::text) ~* '(strategy|market entry|board|capital|transformation|executive)';

-- University study-area tags are stored in profiles.function_area and matched through function_tags.
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['business_finance'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(business|finance|market|budget|price|investment|econom|commercial)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['stem_technical'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(technical|software|system|data|experiment|study tool|AI tool|engineering|science)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['law_policy'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(law|legal|policy|regulat|contract|governance)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['humanities_social'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(essay|seminar|social|research|source|argument|survey|misinformation)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['health_life_sciences'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(health|wellness|clinical|medical|supplement|patient|life science)';
update public.challenges set function_tags=array(select distinct x from unnest(function_tags||array['creative_design'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(design|prototype|creative|media|brand)';

update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['business_finance'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(business|finance|market|budget|price|investment|econom|commercial)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['stem_technical'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(technical|software|system|data|experiment|study tool|AI tool|engineering|science)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['humanities_social'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(essay|seminar|social|research|source|argument|survey|misinformation)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['health_life_sciences'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(health|wellness|clinical|medical|supplement|patient)';
update public.daily_lessons set function_tags=array(select distinct x from unnest(function_tags||array['creative_design'])x) where is_published=true and audience_segments@>array['university_student'] and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(design|prototype|creative|media|brand)';

-- Professional industry/domain tags.
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['technology'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(software|technology|technical|system|cyber|data platform|AI operating|architecture|digital)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['financial_services'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(bank|loan|credit|portfolio|capital allocation|financial service|investment product)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['professional_services'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(client|consult|advisory|proposal|engagement)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['consumer_retail'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(retail|consumer|customer segment|campaign|brand|store|churn)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['healthcare'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(patient|clinical|healthcare|medical|hospital|health claim)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['education'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(university|student|academic|module|essay|dissertation|seminar)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['manufacturing_industrial'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(manufactur|plant|factory|production line|industrial)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['media_creative'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(media|creative|campaign|brand|content)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['construction_real_estate'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(construction|property|real estate|site project|building project)';
update public.challenges set industry_tags=array(select distinct x from unnest(industry_tags||array['public_sector'])x) where is_published=true and (title||' '||prompt||' '||coalesce(scenario_context,'')) ~* '(public sector|government|citizen|public service|regulator)';

update public.daily_lessons set industry_tags=array(select distinct x from unnest(industry_tags||array['technology'])x) where is_published=true and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(software|technology|technical|system|cyber|data platform|AI operating|architecture|digital)';
update public.daily_lessons set industry_tags=array(select distinct x from unnest(industry_tags||array['professional_services'])x) where is_published=true and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(client|consult|advisory|proposal|engagement)';
update public.daily_lessons set industry_tags=array(select distinct x from unnest(industry_tags||array['consumer_retail'])x) where is_published=true and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(retail|consumer|customer|campaign|brand)';
update public.daily_lessons set industry_tags=array(select distinct x from unnest(industry_tags||array['education'])x) where is_published=true and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(university|student|academic|module|essay|seminar)';
update public.daily_lessons set industry_tags=array(select distinct x from unnest(industry_tags||array['financial_services'])x) where is_published=true and (title||' '||content::text||' '||coalesce(scenario_context,'')) ~* '(portfolio|capital allocation|financial|investment)';
