-- Cogni v0.14: remove mechanical prompt cloning from the legacy audience bank without changing scenarios, answer keys or scoring.
with objective(slug,phrase) as (values
('critical-thinking','test the claim before acting'),('ai-output-verification','verify the AI output before relying on it'),('evidence-evaluation','test whether the evidence is strong enough'),('logical-reasoning','check whether the conclusion really follows'),('bias-recognition','reduce the risk of bias distorting the judgement'),('decision-uncertainty','handle the uncertainty without pretending it is gone'),('problem-framing','clarify the real problem before choosing a solution'),('assumption-identification','test the assumption carrying the conclusion'),('correlation-causation','separate a real cause from a coincidental pattern'),('source-quality','check whether the source is trustworthy enough'),('hallucination-detection','verify whether the specific claim is real'),('missing-information','find the missing information most likely to change the decision'),('argument-comparison','compare the competing views fairly'),('better-questions','ask the question most likely to change the decision'),('ai-trust-boundaries','set the right boundary between AI and human judgement')
), candidates as (
 select c.id,unnest(c.audience_segments) audience,c.interaction_type,o.phrase,
 regexp_replace(c.prompt,'\s+(What should you do first to|Choose the TWO actions that would best help you|Put the responses in order from most to least useful for helping you|Sort each response by whether it helps or hurts your ability to|You need to make a call now\. What would you do next to).*$','','i') base
 from public.challenges c
 join lateral (select s.slug from public.challenge_skill_mapping m join public.skills s on s.id=m.skill_id where m.challenge_id=c.id order by m.weight desc nulls last limit 1) sk on true
 join objective o on o.slug=sk.slug
 where c.is_published=true and not c.is_diagnostic and c.challenge_type='judgement_scenario'
), proposed as (
 select id, base || case interaction_type
 when 'single_choice' then case audience when 'university_student' then ' What is the strongest next step to '||phrase||'?' when 'graduate_early_career' then ' What is the strongest professional next step to '||phrase||'?' when 'junior_professional' then ' Which next step would best help you '||phrase||'?' when 'management' then ' As the manager, which response would best help you '||phrase||'?' when 'executive' then ' At executive level, which response would best help you '||phrase||'?' end
 when 'multi_select' then case audience when 'university_student' then ' Choose the TWO checks that would best help you '||phrase||'.' when 'graduate_early_career' then ' Choose the TWO actions that would best help you '||phrase||' at work.' when 'junior_professional' then ' Choose the TWO actions that would most strengthen your recommendation by helping you '||phrase||'.' when 'management' then ' Choose the TWO actions that would best improve the management decision by helping you '||phrase||'.' when 'executive' then ' Choose the TWO actions that would most strengthen the executive decision by helping you '||phrase||'.' end
 when 'ranking' then case audience when 'university_student' then ' Rank these responses from strongest to weakest for helping you '||phrase||'.' when 'graduate_early_career' then ' Rank these workplace responses from strongest to weakest for helping you '||phrase||'.' when 'junior_professional' then ' Rank these responses from strongest to weakest for building a recommendation that can '||phrase||'.' when 'management' then ' Rank these management responses from strongest to weakest for helping you '||phrase||'.' when 'executive' then ' Rank these executive responses from strongest to weakest for helping you '||phrase||'.' end
 when 'classification' then case audience when 'university_student' then ' Sort each response by whether it strengthens or weakens your ability to '||phrase||'.' when 'graduate_early_career' then ' Sort each response by whether it strengthens or weakens your professional ability to '||phrase||'.' when 'junior_professional' then ' Sort each response by whether it strengthens or weakens a recommendation that must '||phrase||'.' when 'management' then ' Sort each response by whether it strengthens or weakens the management judgement needed to '||phrase||'.' when 'executive' then ' Sort each response by whether it strengthens or weakens the executive judgement needed to '||phrase||'.' end
 when 'triage' then case audience when 'university_student' then ' You have to choose a next step. What would you do to '||phrase||'?' when 'graduate_early_career' then ' You need to respond now. What would you do next to '||phrase||'?' when 'junior_professional' then ' You need to recommend a next step. What would you do to '||phrase||'?' when 'management' then ' You need to decide what the team should do. What is the strongest next step to '||phrase||'?' when 'executive' then ' A decision is needed now. What is the strongest next step to '||phrase||'?' end end as new_prompt
 from candidates
)
update public.challenges c set prompt=p.new_prompt,updated_at=now() from proposed p where c.id=p.id;

do $$ begin
 if exists(select 1 from public.challenges where is_published=true group by lower(regexp_replace(trim(prompt),'\s+',' ','g')) having count(*)>1) then
   raise exception 'Audience prompt rewrite created duplicate published prompts';
 end if;
end $$;
