-- Cogni v0.20b — Casual skill templates.
truncate table private._cogni_v020_casual_skill;
insert into private._cogni_v020_casual_skill values
(1,'critical-thinking','Challenge the conclusion','What is the strongest first move before accepting the conclusion?','Separate what is known from what is claimed, then check the evidence and assumptions carrying {claim}.','Look for a credible alternative explanation and ask what evidence would distinguish it.','Accept the conclusion because it fits what you already expected.','Share or act on it immediately because the wording sounds confident.','Strong critical thinking separates observation, interpretation and conclusion before commitment.','Slow down the conclusion long enough to inspect the evidence, assumptions and alternatives.',-1),
(2,'evidence-evaluation','Test the evidence','Which response best tests whether the evidence is strong enough?','Check whether {source} directly tests {claim}, using a relevant sample and a method that could reveal failure.','Look for independent evidence and whether important limitations were disclosed.','Treat a large percentage, star rating or comment count as strong evidence without checking how it was produced.','Rely on popularity or confident presentation instead of the method.','Evidence is useful when its method, relevance and limitations fit the claim being made.','Match the strength of the evidence to the strength and consequence of the claim.',0),
(3,'source-quality','Check the source','What is the strongest way to judge whether the source is trustworthy enough?','Trace the claim to the original source and check its date, method, expertise and incentives.','Compare it with an independent source that could reasonably disagree.','Assume the source is reliable because it looks professional or is widely shared.','Use the claim without locating where it came from.','A polished or popular source can still be outdated, conflicted or one step removed from the evidence.','Trace important claims to their origin and inspect method, recency and incentives.',0),
(4,'assumption-identification','Find the hidden assumption','Which response best exposes the assumption carrying the decision?','Name the condition that must be true for {claim} to support {decision}, then test it.','Ask which hidden link between the evidence and conclusion is most likely to fail.','Debate a minor detail that would not change the decision.','Treat the conclusion as self-evident because it sounds plausible.','The most important assumption is the condition that connects the evidence to the proposed action.','Find and test the assumption that would most change the decision if it were false.',0),
(5,'better-questions','Ask the useful question','Which question has the highest value for the decision?','Ask: “What single answer would most change whether {decision} is sensible?”','Ask for the missing fact most likely to reverse or qualify the recommendation.','Ask broad questions that produce more information but not a clearer decision.','Ask only for reassurance that the current choice is right.','A useful question changes what you would do, rather than merely adding detail.','Prioritise the question whose answer is most likely to change the choice.',-2),
(6,'bias-recognition','Spot the pull on judgement','Which response best reduces the risk of bias distorting the choice?','Check whether vivid stories, familiarity or your preferred outcome are receiving more weight than the full evidence.','Deliberately look for evidence that would make the opposite choice more reasonable.','Assume awareness of bias means it cannot affect you.','Choose the option that confirms your first impression.','Bias often changes which evidence feels important before we consciously evaluate it.','Create a deliberate check for the evidence your first impression is most likely to ignore.',-1),
(7,'correlation-causation','Separate pattern from cause','What is the strongest next step before claiming cause and effect?','Treat the pattern as a clue and test other causes, selection effects and timing changes before claiming cause.','Look for a credible comparison that separates {claim} from {alternative}.','Call it causal because one change happened before the other.','Ignore other changes that happened at the same time.','A pattern can be real without showing what caused it.','Before claiming cause, test alternative explanations and seek a credible comparison.',1),
(8,'decision-uncertainty','Decide without fake certainty','Which response handles the remaining uncertainty most effectively?','Compare options using what matters, show the remaining uncertainty and choose a reversible next step where possible.','Set a threshold for acting and identify the signal that would make you revise the choice.','Wait for complete certainty even though the delay has a cost.','Hide uncertainty and present the preferred option as guaranteed.','Good judgement makes uncertainty visible while still enabling proportionate action.','Act at the right level of confidence and preserve the ability to learn or reverse course.',1),
(9,'problem-framing','Define the real problem','Which response best clarifies the problem before choosing a solution?','State the actual outcome you need and the cause of the problem before choosing a solution.','Ask whether the proposed action addresses the real problem or only its most visible symptom.','Optimise the first solution suggested without checking the goal.','Define the problem as “we need this product or action”.','A solution can look attractive while solving the wrong problem.','Define the outcome, cause and constraints before comparing solutions.',-2),
(10,'missing-information','Find the fact that matters','Which response best finds the missing information most likely to change the decision?','Find the missing fact most likely to change the choice, not the easiest fact to collect.','Identify which uncertainty carries the largest downside if wrong.','Collect more background information without prioritising decision value.','Proceed as though missing information cannot matter.','Not every unknown deserves equal effort; the most valuable fact is the one that can change the action.','Search first for the missing information with the highest decision value.',0),
(11,'argument-comparison','Compare both views fairly','Which response gives the fairest comparison of the competing views?','Compare both views against the same criteria, evidence standards and possible failure cases.','State the strongest version of each argument before judging them.','Count how many points each side makes without weighting their quality.','Use the confidence or popularity of the speaker as the deciding factor.','A fair comparison puts competing views on the same evidential and decision criteria.','Strengthen each argument, then compare both using the same standards.',1),
(12,'logical-reasoning','Check whether it follows','Which response best checks whether the conclusion really follows?','Check whether the facts actually support the conclusion and whether any step in the reasoning is missing.','Test whether the same evidence could support a different conclusion.','Accept the conclusion because each sentence sounds individually reasonable.','Treat repetition of the conclusion as proof.','Reasoning fails when a plausible conclusion is not actually supported by the stated facts.','Inspect every link between evidence and conclusion, including what is left unstated.',2),
(13,'ai-output-verification','Verify the AI answer','Which response best checks the AI output before relying on it?','Verify the high-impact details against the original or authoritative source before relying on the AI answer.','Separate parts you can verify from suggestions that should remain provisional.','Ask the same AI again and treat consistency as confirmation.','Rely on the AI because it gave precise details.','AI can produce fluent, specific information without a reliable connection to the underlying facts.','Verify the details that carry the consequence of the decision, not just the easy details.',1),
(14,'hallucination-detection','Check for invented detail','Which response best checks whether a specific detail may be made up?','Check whether the named fact, quote, place, rule or source actually exists and says what the answer claims.','Look for invented specificity, unsupported citations or details that cannot be traced.','Paraphrase the claim so the source no longer needs checking.','Assume a detailed answer is too specific to be fabricated.','Specificity can create an illusion of accuracy; traceability is the stronger test.','Treat untraceable specificity as a warning signal, especially when the detail changes the action.',2),
(15,'ai-trust-boundaries','Set the human boundary','Which response sets the strongest boundary for using AI in this decision?','Keep a person responsible for checking any part that could affect health, money, rights, safety or an irreversible commitment.','Use AI to generate options, while retaining human judgement for the final decision and sensitive data.','Let AI decide automatically whenever it reports high confidence.','Share sensitive information and follow the output without review.','The more consequential, sensitive or irreversible the decision, the stronger the human control should be.','Use AI to extend judgement, not to remove human responsibility from consequential choices.',2);
