-- Cogni v0.20e — Casual lessons, part one.
insert into public.daily_lessons(
 slug,title,subtitle,emoji,skill_id,content,estimated_minutes,is_published,sort_order,audience_segments,
 difficulty,scenario_context,content_key,function_tags,industry_tags,goal_tags,scenario_category,
 complexity_level,created_at,updated_at
) values
('casual-critical-thinking','Pause before the conclusion','Separate what happened from what someone says it means.','🧭',(select id from public.skills where slug='critical-thinking'),'{"story":"A short video gives a strong conclusion first, then adds a few facts that seem to support it.","twist":"The facts may be accurate while the conclusion still depends on hidden assumptions or missing alternatives.","principle":"Separate observation, interpretation and conclusion before deciding what to believe or do.","try_it":"Take one confident claim you saw today. Write what is directly known, what is inferred and what remains uncertain.","reveal":"The thinking move is to slow the conclusion down long enough to inspect the links carrying it.","ai_age":"AI often makes conclusions sound complete. Ask it to label evidence, assumptions and alternatives, then verify the important facts."}'::jsonb,3,true,22001,array['casual']::text[],48,'Everyday learner • A confident online claim','v020_casual_lesson_critical-thinking',array['news_media','personal_growth']::text[],'{}'::text[],array['think_more_clearly','understand_news_online']::text[],'a confident online claim',1,now(),now()),
('casual-evidence-evaluation','Match evidence to the claim','Strong wording needs evidence that can actually support it.','🔎',(select id from public.skills where slug='evidence-evaluation'),'{"story":"A product advert uses an impressive percentage from a test that sounds scientific.","twist":"The result may only apply to narrow test conditions, a small sample or a different outcome from the one you care about.","principle":"Judge evidence by method, relevance, sample and limitations—not by how impressive the number looks.","try_it":"Choose one statistic you encountered. Ask what was measured, compared, omitted and whether it matches your decision.","reveal":"The useful move is not “Is there evidence?” but “Is this evidence capable of supporting this claim?”","ai_age":"Ask AI to explain a study, but check the original source before relying on sample size, method or result."}'::jsonb,3,true,22002,array['casual']::text[],50,'Everyday learner • A product statistic','v020_casual_lesson_evidence-evaluation',array['money_purchases','health_wellbeing']::text[],'{}'::text[],array['spot_misleading_claims','make_better_everyday_decisions']::text[],'a product statistic',2,now(),now()),
('casual-source-quality','Trace the claim to its source','The source behind the source often changes the story.','🧵',(select id from public.skills where slug='source-quality'),'{"story":"An article repeats a claim from another article, which refers vaguely to “research”.","twist":"Each retelling can remove caveats, dates, incentives and the method that would let you judge the claim.","principle":"Trace important claims to their origin and check recency, expertise, method and incentives.","try_it":"Follow one shared claim back as far as you can. Note where the evidence ends and commentary begins.","reveal":"Trust comes from traceability and method, not from a professional layout or popularity.","ai_age":"AI can help locate candidate sources, but invented or mismatched citations are possible. Open and inspect them."}'::jsonb,3,true,22003,array['casual']::text[],50,'Everyday learner • A widely shared article','v020_casual_lesson_source-quality',array['news_media','technology_ai']::text[],'{}'::text[],array['understand_news_online','spot_misleading_claims']::text[],'a widely shared article',2,now(),now()),
('casual-assumption-identification','Find the condition carrying the choice','Every recommendation relies on something being true.','🧩',(select id from public.skills where slug='assumption-identification'),'{"story":"A cheaper-looking option seems obviously better because one headline feature is attractive.","twist":"The conclusion may depend on usage, hidden costs, quality, timing or a need the option does not meet.","principle":"Name the condition that must be true for the evidence to support the proposed action.","try_it":"Finish this sentence for a current choice: “This option is best only if…” Then test the most important condition.","reveal":"The strongest assumption is the one that would most change the decision if false.","ai_age":"Ask AI to list assumptions, then decide which are factual, testable and consequential."}'::jsonb,3,true,22004,array['casual']::text[],50,'Everyday learner • A “better value” offer','v020_casual_lesson_assumption-identification',array['money_purchases','personal_growth']::text[],'{}'::text[],array['ask_better_questions','make_better_everyday_decisions']::text[],'a “better value” offer',2,now(),now()),
('casual-better-questions','Ask the question that changes the decision','More information is not always more useful.','❓',(select id from public.skills where slug='better-questions'),'{"story":"You can ask dozens of questions, but time is limited and most answers would not alter your choice.","twist":"The best question is often the one whose answer could reverse the decision, change the timing or reduce the largest downside.","principle":"Prioritise questions by decision value, not by how easy they are to answer.","try_it":"Write one question beginning: “What answer would make me choose differently?”","reveal":"A high-value question reduces the uncertainty that matters, rather than simply adding detail.","ai_age":"Use AI to generate questions, then rank them by how much each answer could change your action."}'::jsonb,3,true,22005,array['casual']::text[],48,'Everyday learner • Planning a purchase or trip','v020_casual_lesson_better-questions',array['travel_planning','money_purchases']::text[],'{}'::text[],array['ask_better_questions','make_better_everyday_decisions']::text[],'planning a purchase or trip',1,now(),now()),
('casual-bias-recognition','Notice what is pulling your attention','Vivid stories and preferred outcomes can outweigh better evidence.','🪞',(select id from public.skills where slug='bias-recognition'),'{"story":"One dramatic story is easier to remember than a large set of ordinary results.","twist":"What feels important may reflect vividness, familiarity, social proof or a desire for a particular answer.","principle":"Create a deliberate check for the evidence your first impression is most likely to ignore.","try_it":"For one current opinion, ask what evidence would make the opposite view more reasonable.","reveal":"Bias control is not claiming neutrality; it is changing the process so neglected evidence gets a fair hearing.","ai_age":"AI can reinforce your framing. Ask for the strongest counter-case and verify it independently."}'::jsonb,3,true,22006,array['casual']::text[],49,'Everyday learner • A memorable recommendation','v020_casual_lesson_bias-recognition',array['news_media','relationships_communication']::text[],'{}'::text[],array['think_more_clearly','understand_news_online']::text[],'a memorable recommendation',2,now(),now()),
('casual-correlation-causation','A pattern is a clue, not a cause','Several explanations can fit the same change.','🔗',(select id from public.skills where slug='correlation-causation'),'{"story":"Two things move together: a new habit and a better score, mood or result.","twist":"Timing, selection, a third factor or normal variation can create the same pattern.","principle":"Before claiming cause, test alternative explanations and look for a credible comparison.","try_it":"List two other reasons the observed pattern could have occurred.","reveal":"The aim is not to dismiss the pattern, but to avoid acting as though its cause is already known.","ai_age":"Ask AI for alternative explanations and a simple test, but do not treat plausible mechanisms as proof."}'::jsonb,3,true,22007,array['casual']::text[],51,'Everyday learner • A personal tracker pattern','v020_casual_lesson_correlation-causation',array['health_wellbeing','personal_growth']::text[],'{}'::text[],array['think_more_clearly','make_better_everyday_decisions']::text[],'a personal tracker pattern',2,now(),now()),
('casual-decision-uncertainty','Act without pretending certainty','A good decision can still have an uncertain outcome.','🌦️',(select id from public.skills where slug='decision-uncertainty'),'{"story":"You must decide before all the information is available, and both acting and waiting have costs.","twist":"Waiting for certainty can itself be a decision, while acting too confidently can remove useful options.","principle":"Set an action threshold, compare downsides and preserve reversibility where possible.","try_it":"Define the signal that would make you act now, wait or switch to a backup plan.","reveal":"Good judgement makes uncertainty visible while still choosing a proportionate next step.","ai_age":"Use AI for scenarios and options, not for fake certainty. Keep responsibility for the final choice."}'::jsonb,3,true,22008,array['casual']::text[],51,'Everyday learner • A weather-dependent plan','v020_casual_lesson_decision-uncertainty',array['travel_planning','personal_growth']::text[],'{}'::text[],array['make_better_everyday_decisions','think_more_clearly']::text[],'a weather-dependent plan',2,now(),now())
on conflict(slug) do update set
 title=excluded.title,subtitle=excluded.subtitle,emoji=excluded.emoji,skill_id=excluded.skill_id,
 content=excluded.content,estimated_minutes=excluded.estimated_minutes,is_published=true,
 sort_order=excluded.sort_order,audience_segments=excluded.audience_segments,difficulty=excluded.difficulty,
 scenario_context=excluded.scenario_context,content_key=excluded.content_key,function_tags=excluded.function_tags,
 industry_tags=excluded.industry_tags,goal_tags=excluded.goal_tags,scenario_category=excluded.scenario_category,
 complexity_level=excluded.complexity_level,updated_at=now();
