-- Cogni v0.20f — Casual lessons, part two and parity validation.
insert into public.daily_lessons(
 slug,title,subtitle,emoji,skill_id,content,estimated_minutes,is_published,sort_order,audience_segments,
 difficulty,scenario_context,content_key,function_tags,industry_tags,goal_tags,scenario_category,
 complexity_level,created_at,updated_at
) values
('casual-problem-framing','Solve the real problem','The first proposed solution can hide the actual need.','🎯',(select id from public.skills where slug='problem-framing'),'{"story":"A new app or product is proposed before anyone clearly states the outcome they need.","twist":"Optimising the suggested solution can waste effort if the underlying problem is different or smaller.","principle":"Define the outcome, cause and constraints before comparing solutions.","try_it":"Rewrite one “We need X” statement as “We need to achieve Y because Z.”","reveal":"A better frame creates more useful options and prevents commitment to a solution disguised as a problem.","ai_age":"Ask AI for alternative problem frames, then validate them with the people and facts involved."}'::jsonb,3,true,22009,array['casual']::text[],48,'Everyday learner • A technology fix','v020_casual_lesson_problem-framing',array['technology_ai','personal_growth']::text[],'{}'::text[],array['ask_better_questions','think_more_clearly']::text[],'a technology fix',1,now(),now()),
('casual-missing-information','Find the missing fact with the highest value','Not every unknown deserves equal effort.','🕳️',(select id from public.skills where slug='missing-information'),'{"story":"You have plenty of background information but one unresolved fact could still change the choice.","twist":"Collecting easy details can create activity without reducing the uncertainty that carries the risk.","principle":"Search first for the missing information most likely to change the action.","try_it":"Ask: “Which unknown would make me reverse, delay or redesign this decision?”","reveal":"Information has decision value when it can alter the choice or the downside—not merely fill a gap.","ai_age":"Use AI to identify possible unknowns, but verify which are real and consequential in your situation."}'::jsonb,3,true,22010,array['casual']::text[],50,'Everyday learner • An incomplete recommendation','v020_casual_lesson_missing-information',array['money_purchases','travel_planning']::text[],'{}'::text[],array['ask_better_questions','make_better_everyday_decisions']::text[],'an incomplete recommendation',2,now(),now()),
('casual-argument-comparison','Compare both views by the same standard','Fair comparison is stronger than counting talking points.','⚖️',(select id from public.skills where slug='argument-comparison'),'{"story":"Two sides use different evidence, language and definitions while each presents its strongest examples.","twist":"You can unintentionally demand rigorous proof from one side and accept anecdotes from the other.","principle":"State the strongest version of each view, then compare both using the same criteria and failure tests.","try_it":"Write the best case for each side in two sentences, then list one shared decision criterion.","reveal":"A fair process does not guarantee equal conclusions; it gives both arguments an equal test.","ai_age":"Ask AI to steelman both sides, then inspect sources and omissions rather than trusting symmetry."}'::jsonb,3,true,22011,array['casual']::text[],51,'Everyday learner • A disputed community issue','v020_casual_lesson_argument-comparison',array['community_civic','relationships_communication']::text[],'{}'::text[],array['understand_news_online','think_more_clearly']::text[],'a disputed community issue',2,now(),now()),
('casual-logical-reasoning','Check every link in the reasoning','A plausible conclusion does not prove that it follows.','🧠',(select id from public.skills where slug='logical-reasoning'),'{"story":"Each sentence in an argument sounds reasonable, so the conclusion feels inevitable.","twist":"A missing link, shifted definition or unsupported generalisation can hide between individually plausible statements.","principle":"Test whether the stated facts require the conclusion and whether another conclusion also fits.","try_it":"Turn one argument into “Because A, therefore B.” Then ask what must connect A to B.","reveal":"Reasoning quality depends on the links, not just the plausibility of the starting facts and final claim.","ai_age":"Ask AI to expose the argument structure, then check each premise and inference yourself."}'::jsonb,3,true,22012,array['casual']::text[],52,'Everyday learner • A persuasive explanation','v020_casual_lesson_logical-reasoning',array['news_media','personal_growth']::text[],'{}'::text[],array['think_more_clearly','spot_misleading_claims']::text[],'a persuasive explanation',2,now(),now()),
('casual-ai-output-verification','Verify the detail that carries the consequence','Fluent AI output is not the same as checked information.','🤖',(select id from public.skills where slug='ai-output-verification'),'{"story":"An AI answer gives a precise time, rule, price or citation that would materially affect your plan.","twist":"The answer can be coherent and specific while outdated, unsupported or linked to the wrong source.","principle":"Check high-impact details against the current original or authoritative source.","try_it":"Identify the one AI-provided detail that would cost you most if wrong, then verify it independently.","reveal":"Verification effort should follow consequence: check what carries the decision, not only what is easy.","ai_age":"Consistency across repeated AI answers is not independent confirmation; trace the claim outside the model."}'::jsonb,3,true,22013,array['casual']::text[],51,'Everyday learner • An AI travel or policy answer','v020_casual_lesson_ai-output-verification',array['technology_ai','travel_planning']::text[],'{}'::text[],array['use_ai_wisely','make_better_everyday_decisions']::text[],'an ai travel or policy answer',2,now(),now()),
('casual-hallucination-detection','Treat untraceable specificity as a warning','Detail can create an illusion of accuracy.','🫥',(select id from public.skills where slug='hallucination-detection'),'{"story":"An AI or post gives a specific person, clause, study, place or quotation that sounds authoritative.","twist":"Invented detail often looks more credible precisely because it is concrete.","principle":"Check whether the named fact exists and whether the source actually says what is claimed.","try_it":"Open one cited source and search for the exact claim rather than only confirming the page exists.","reveal":"Traceability is a stronger signal than specificity.","ai_age":"Ask for sources, but regard them as leads. Verify titles, dates, authors and the actual supporting passage."}'::jsonb,3,true,22014,array['casual']::text[],52,'Everyday learner • A named quote or rule','v020_casual_lesson_hallucination-detection',array['technology_ai','news_media']::text[],'{}'::text[],array['use_ai_wisely','spot_misleading_claims']::text[],'a named quote or rule',2,now(),now()),
('casual-ai-trust-boundaries','Keep a human boundary around consequential choices','The stakes determine how much control to retain.','🛡️',(select id from public.skills where slug='ai-trust-boundaries'),'{"story":"AI can quickly generate options and explanations for a decision involving money, health, rights, safety or private information.","twist":"Convenience can obscure who remains accountable, what data was shared and what happens if the answer is wrong.","principle":"Increase human review, authoritative verification and privacy protection as consequences rise.","try_it":"Classify a current AI use as low, medium or high consequence. Define what must stay under human control.","reveal":"AI can extend judgement without replacing responsibility.","ai_age":"Use AI for exploration and drafting; retain qualified human or authoritative checks for consequential decisions."}'::jsonb,3,true,22015,array['casual']::text[],52,'Everyday learner • A sensitive or irreversible decision','v020_casual_lesson_ai-trust-boundaries',array['technology_ai','personal_growth']::text[],'{}'::text[],array['use_ai_wisely','make_better_everyday_decisions']::text[],'a sensitive or irreversible decision',2,now(),now()),
('casual-integrated','The everyday verification loop','Combine the skills when a claim is urgent, specific and consequential.','🔄',(select id from public.skills where slug='critical-thinking'),'{"story":"A trusted person shares an AI-written recommendation, an official-looking link and pressure to act quickly.","twist":"Trust, urgency, specificity and social proof can all make separate weaknesses feel like confirmation.","principle":"Pause, frame the decision, trace the claim, test evidence and assumptions, consider alternatives, then act in proportion to uncertainty and consequence.","try_it":"Use the loop on one real claim: What is the decision? What is known? What must be verified? What could change the choice? What is the safest reversible next step?","reveal":"The power comes from sequencing the checks, not performing each skill in isolation.","ai_age":"Let AI help generate questions and alternatives, while independent sources and human responsibility control the final action."}'::jsonb,3,true,22016,array['casual']::text[],53,'Everyday learner • An urgent group-chat recommendation','v020_casual_lesson_integrated',array['technology_ai','relationships_communication','money_purchases']::text[],'{}'::text[],array['use_ai_wisely','spot_misleading_claims','make_better_everyday_decisions']::text[],'an urgent group-chat recommendation',3,now(),now())
on conflict(slug) do update set
 title=excluded.title,subtitle=excluded.subtitle,emoji=excluded.emoji,skill_id=excluded.skill_id,
 content=excluded.content,estimated_minutes=excluded.estimated_minutes,is_published=true,
 sort_order=excluded.sort_order,audience_segments=excluded.audience_segments,difficulty=excluded.difficulty,
 scenario_context=excluded.scenario_context,content_key=excluded.content_key,function_tags=excluded.function_tags,
 industry_tags=excluded.industry_tags,goal_tags=excluded.goal_tags,scenario_category=excluded.scenario_category,
 complexity_level=excluded.complexity_level,updated_at=now();

do $$
declare
  challenge_n integer; lesson_n integer; diagnostic_n integer; skills_n integer;
  missing_keys integer; missing_mappings integer; duplicate_prompts integer;
  single_n integer; multi_n integer; ranking_n integer; classification_n integer; triage_n integer;
  min_d integer; max_d integer; mean_d numeric;
begin
  select count(*),count(*) filter(where is_diagnostic),min(difficulty),max(difficulty),round(avg(difficulty)::numeric,1)
  into challenge_n,diagnostic_n,min_d,max_d,mean_d
  from public.challenges where is_published and audience_segments=array['casual']::text[];
  if challenge_n<>126 then raise exception 'Casual audience expected 126 published challenges, found %',challenge_n; end if;
  if diagnostic_n<>5 then raise exception 'Casual audience expected 5 diagnostics, found %',diagnostic_n; end if;
  if min_d<44 or max_d>57 or mean_d<49 or mean_d>52 then raise exception 'Casual difficulty distribution invalid: min %, max %, mean %',min_d,max_d,mean_d; end if;

  select count(distinct m.skill_id) into skills_n from public.challenges c join public.challenge_skill_mapping m on m.challenge_id=c.id where c.is_published and c.audience_segments=array['casual']::text[];
  if skills_n<>15 then raise exception 'Casual audience expected 15 skills, found %',skills_n; end if;

  select count(*) into missing_keys from public.challenges c left join public.challenge_answer_keys k on k.challenge_id=c.id where c.is_published and c.audience_segments=array['casual']::text[] and k.challenge_id is null;
  if missing_keys<>0 then raise exception 'Casual audience has % challenges without answer keys',missing_keys; end if;
  select count(*) into missing_mappings from public.challenges c left join public.challenge_skill_mapping m on m.challenge_id=c.id where c.is_published and c.audience_segments=array['casual']::text[] and m.challenge_id is null;
  if missing_mappings<>0 then raise exception 'Casual audience has % challenges without skill mappings',missing_mappings; end if;

  select count(*) filter(where interaction_type='single_choice'),count(*) filter(where interaction_type='multi_select'),count(*) filter(where interaction_type='ranking'),count(*) filter(where interaction_type='classification'),count(*) filter(where interaction_type='triage')
  into single_n,multi_n,ranking_n,classification_n,triage_n from public.challenges where is_published and audience_segments=array['casual']::text[];
  if single_n<>55 or multi_n<>18 or ranking_n<>19 or classification_n<>17 or triage_n<>17 then
    raise exception 'Casual format parity invalid: single %, multi %, ranking %, classification %, triage %',single_n,multi_n,ranking_n,classification_n,triage_n;
  end if;

  select count(*) into lesson_n from public.daily_lessons where is_published and audience_segments=array['casual']::text[];
  if lesson_n<>16 then raise exception 'Casual audience expected 16 published lessons, found %',lesson_n; end if;

  select count(*) into duplicate_prompts from (
    select lower(regexp_replace(btrim(prompt),'\s+',' ','g')) normalized,count(*)
    from public.challenges where is_published group by 1 having count(*)>1
  ) d;
  if duplicate_prompts<>0 then raise exception 'Published challenge prompt duplication detected after casual migration'; end if;
end $$;

drop table if exists private._cogni_v020_casual_generated;
drop table if exists private._cogni_v020_casual_scenario;
drop table if exists private._cogni_v020_casual_skill;
drop function if exists private._cogni_casual_render(text,text,text,text,text);
